### ISSUE TITLE
Wiedererkennbarkeit

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#10]
> - Die Wiedererkennbarkeit ist wegen den fehlenden Farben (grüner Rahmen, blaue Rubrikleiste) und Foto-Banner nicht gegeben.

ich kann schauen was sich machen lässt, aber ein stückweit müssen wir einfach mit dem neuen layout leben. Ich hatte dies zu Beginn bereits angesprochen

**Comment by wicoz** [comment]
Hintergrundfarbe der Website (grün) und der Rubrikenleiste (dunkelblau) lässt sich nicht einfach am Original angleichen?

**Comment by ratnanil** [comment]
es geht schon, mir gefällts aber nicht besonders. dir?


https://wieselundco.github.io/website/Ausgangslage-und-Ziele.html

![grafik](https://user-images.githubusercontent.com/12532091/127986724-b1c1808f-d90d-421a-9d21-133573ce6cc6.png)

**Comment by wicoz** [comment]
@ratnanil  
Blaue Kopfzeile find ich gut, danke. 
Nun ja, wenn der Hintergrund auch hinter den Fotos und dem Text die olive Farbe hat, dann find ichs auch too much. 
Bitte ändern auf weiss.

**Comment by ratnanil** [comment]
![grafik](https://user-images.githubusercontent.com/12532091/128135574-07b0c120-3e11-47f0-aada-efe0376f9e5f.png)
