### ISSUE TITLE
viele Bilder fehlen

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#12]

**Comment by ratnanil** [comment]
Abgesehen von den Bildergalerien meinst du? Kannst du ein paar Beispiele liefern?

**Comment by wicoz** [comment]
U.a. unter über uns-> partner

Nils ***@***.***> schrieb am Do., 24. Juni 2021, 06:44:

**Comment by ratnanil** [comment]
wir hatten für all "über uns" artikel schon im Original (http://wieselundco.ch/ueber-uns) keine bilder

**Comment by wicoz** [comment]
-> Partner

Nils ***@***.***> schrieb am Do., 24. Juni 2021, 07:12:

**Comment by ratnanil** [comment]
Kannst du etwas ausformulieren? Du meinst die Bilder hier: https://wieselundco.github.io/website/ueber-uns/7-partner/ ?

**Comment by wicoz** [comment]
Jep. Gestern waren sie noch nicht da

Nils ***@***.***> schrieb am Do., 24. Juni 2021, 15:35:

**Comment by ratnanil** [comment]
bildergallerien werden in #3 behandelt
