### ISSUE TITLE
(short-)Links testen wenn die webseite über wieselundco.ch läuft

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#13]

**Comment by ratnanil** [comment]
da bin ich dran

**Comment by ratnanil** [comment]
|V3                                                                                                                                                                           |file                                                                                                                    |
|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------|
|https://www.youtube.com/watch?v=82V8zapGEWI&t=36s                                                                                                                            |./_faszination-kleinraubtiere-mensch-wiesel/115-vernetzungsideen/115-vernetzungsideen.Rmd                               |
|http://wieselundco.ch/images/dokumente/wiselquiz/Wieselantworten_Web.pdf                                                                                                     |./_faszination-kleinraubtiere-unsere-leitarten/36-fragen-rund-um-die-wiesel/36-fragen-rund-um-die-wiesel.Rmd            |
|http://wieselundco.ch/images/dokumente/wiselquiz/WieselUndWiesel.pdf                                                                                                         |./_faszination-kleinraubtiere-unsere-leitarten/37-fragen-rund-um-die-wiesel-2/37-fragen-rund-um-die-wiesel-2.Rmd        |
|http://wieselundco.ch/images/dokumente/wiselquiz/WieselUndWiesel-gelost.pdf                                                                                                  |./_faszination-kleinraubtiere-unsere-leitarten/37-fragen-rund-um-die-wiesel-2/37-fragen-rund-um-die-wiesel-2.Rmd        |
|https://www.youtube.com/channel/UC3WA9IQb1p8hvPwSAHeefSQ/videos                                                                                                              |./_faszination-kleinraubtiere-unsere-leitarten/41-spannende-kurzfilme/41-spannende-kurzfilme.Rmd                        |
|index.php/beobachtung-melden                                                                                                                                                 |./_mithelfen-anpacken-beobachtung/28-warum-und-wozu-hilft-meine-sichtungs-/28-warum-und-wozu-hilft-meine-sichtungs-.Rmd |
|index.php/beobachtung-melden                                                                                                                                                 |./_mithelfen-anpacken-beobachtung/28-warum-und-wozu-hilft-meine-sichtungs-/28-warum-und-wozu-hilft-meine-sichtungs-.Rmd |
|mailto:thomas.kuensch@oswaedenswil.ch                                                                                                                                        |./_mithelfen-anpacken-mithelfen/108-wieselwerk-mit-schulklassen/108-wieselwerk-mit-schulklassen.Rmd                     |
|ueber-uns/7-partner                                                                                                                                                          |./_news/2016-01-29-69-souvenir-helferessen/2016-01-29-69-souvenir-helferessen.Rmd                                       |
|http://goo.gl/forms/p06Q4LO7VX                                                                                                                                               |./_news/2016-02-26-70-mit-ferienpass-kleinstruktu/2016-02-26-70-mit-ferienpass-kleinstruktu.Rmd                         |
|http://chueweidli.ch/                                                                                                                                                        |./_news/2016-03-08-71-aststrukturen-bauen-sa-12-m/2016-03-08-71-aststrukturen-bauen-sa-12-m.Rmd                         |
|https://www.google.com/url?q=https://goo.gl/forms/6kydQp1sDhqOFjP33&sa=D&usd=2&usg=AOvVaw1JNT8VTkfOsrouo0vtxd29                                                              |./_news/2019-10-16-116-workshop-wuehlmaeuse-im-gr/2019-10-16-116-workshop-wuehlmaeuse-im-gr.Rmd                         |
|https://map.wanderland.ch/?lang=de&p=&route=all&photos=yes&logo=yes&season=summer&resolution=1.01&E=2692342&N=1226467&bgLayer=pk&layers=Wanderland%2CStation&trackId=6665128 |./_news/2021-06-24-viel-glck-auf-der-wieselpirsch/viel-glck-auf-der-wieselpirsch.Rmd                                    |
|BirdLifeZurich-Wieselpirsch.pdf                                                                                                                                              |./_news/2021-06-24-viel-glck-auf-der-wieselpirsch/viel-glck-auf-der-wieselpirsch.Rmd                                    |
|http://wieselundco.ch/projekt/massnahmen/62-wir-unterstuetzen-die-instanstellung-von-feldscheunen)                                                                           |./_projekt-1-1-untersuetzung/61-bonus-system-zur-verguetung-von-massn/61-bonus-system-zur-verguetung-von-massn.Rmd      |
|http://www.nv-schoenenberg.ch/joomla/index.php                                                                                                                               |./_projekt-ausgangslage/11-das-wieselfoerderprojekt-der-gemeinde/11-das-wieselfoerderprojekt-der-gemeinde.Rmd           |
|images/dokumente/Schlussbericht_Schoenenberg.pdf                                                                                                                             |./_projekt-ausgangslage/11-das-wieselfoerderprojekt-der-gemeinde/11-das-wieselfoerderprojekt-der-gemeinde.Rmd           |
|http://www.nv-schoenenberg.ch/                                                                                                                                               |./_projekt-ausgangslage/11-das-wieselfoerderprojekt-der-gemeinde/11-das-wieselfoerderprojekt-der-gemeinde.Rmd           |
|http://www.wieselundco.ch/projekt/massnahmen                                                                                                                                 |./_projekt-ausgangslage/3-ziele-des-projekts-wiesel-co-am-zimmer/3-ziele-des-projekts-wiesel-co-am-zimmer.Rmd           |
|index.php/die-traegerschaft/23-organigramm                                                                                                                                   |./_projekt-ausgangslage/3-ziele-des-projekts-wiesel-co-am-zimmer/3-ziele-des-projekts-wiesel-co-am-zimmer.Rmd           |
|http://www.wieselundco.ch/projekt/ausgangslage/66-beschrieb-umsetzungsphase                                                                                                  |./_projekt-ausgangslage/3-ziele-des-projekts-wiesel-co-am-zimmer/3-ziele-des-projekts-wiesel-co-am-zimmer.Rmd           |
|images/dokumente/Bonussystem_WiCoZ.pdf                                                                                                                                       |./_projekt-ausgangslage/66-beschrieb-umsetzungsphase/66-beschrieb-umsetzungsphase.Rmd                                   |
|ueber-uns/7-partner                                                                                                                                                          |./_projekt-ausgangslage/66-beschrieb-umsetzungsphase/66-beschrieb-umsetzungsphase.Rmd                                   |
|http://www.wieselundco.ch/news/2-uncategorised/88-musteliden-und-reptilien-win-karch-pilotprojekt                                                                            |./_projekt-massnahmen/114-hinweise-haufen/114-hinweise-haufen.Rmd                                                       |
|https://www.zauneidechse.ch/                                                                                                                                                 |./_projekt-massnahmen/114-hinweise-haufen/114-hinweise-haufen.Rmd                                                       |
|https://www.youtube.com/watch?v=xJ9-ijG-5SE                                                                                                                                  |./_projekt-massnahmen/114-hinweise-haufen/114-hinweise-haufen.Rmd                                                       |
|images/dokumente/Bonussystem_WiCoZ.pdf                                                                                                                                       |./_projekt-massnahmen/135-winterquartier/135-winterquartier.Rmd                                                         |
|projekt/ausgangslage                                                                                                                                                         |./_projekt-resultate/118-ueberarbeitete-karten-fuer-massnahme/118-ueberarbeitete-karten-fuer-massnahme.Rmd              |
|http://www.wieselundco.ch/massnahmenkarte                                                                                                                                    |./_projekt-resultate/118-ueberarbeitete-karten-fuer-massnahme/118-ueberarbeitete-karten-fuer-massnahme.Rmd              |
|http://www.wieselundco.ch/sichtungskarte                                                                                                                                     |./_projekt-resultate/118-ueberarbeitete-karten-fuer-massnahme/118-ueberarbeitete-karten-fuer-massnahme.Rmd              |
|http://www.cscf.ch/                                                                                                                                                          |./_projekt-resultate/118-ueberarbeitete-karten-fuer-massnahme/118-ueberarbeitete-karten-fuer-massnahme.Rmd              |
|http://www.wieselundco.ch/images/dokumente/beschrieb_umsetzungsphase/AnhangC_Patch_Vernetzungsplanung.pdf                                                                    |./_projekt-resultate/118-ueberarbeitete-karten-fuer-massnahme/118-ueberarbeitete-karten-fuer-massnahme.Rmd              |
|http://www.wieselundco.ch/wissenschaft/externe-projekte/126-mammaliabox                                                                                                      |./_projekt-resultate/125-wk-etappe1/125-wk-etappe1.Rmd                                                                  |
|http://www.wieselundco.ch/images/Wirkungskontrolle/WK_Master_2016.xlsx                                                                                                       |./_projekt-resultate/80-massnahmen-sind-nachweislich-attrakti/80-massnahmen-sind-nachweislich-attrakti.Rmd              |
|http://www.schluchtalhof.ch/                                                                                                                                                 |./_ueber-uns/23-organigramm/23-organigramm.Rmd                                                                          |
|http://www.biohof-steinacher.ch                                                                                                                                              |./_ueber-uns/23-organigramm/23-organigramm.Rmd                                                                          |
|http://www.aln.zh.ch/internet/baudirektion/aln/de/fjv.html                                                                                                                   |./_ueber-uns/23-organigramm/23-organigramm.Rmd                                                                          |
|http://www.wieselnetz.ch/                                                                                                                                                    |./_ueber-uns/23-organigramm/23-organigramm.Rmd                                                                          |
|http://www.birdlife-zuerich.ch                                                                                                                                               |./_ueber-uns/23-organigramm/23-organigramm.Rmd                                                                          |
|http://www.lsfm.zhaw.ch/de/science/institute-zentren/iunr-integrativeoekologie/wilma.html                                                                                    |./_ueber-uns/23-organigramm/23-organigramm.Rmd                                                                          |
|http://www.lsfm.zhaw.ch/de/science/institute-zentren/iunr-integrativeoekologie/geoinformatik.html                                                                            |./_ueber-uns/23-organigramm/23-organigramm.Rmd                                                                          |
|http://wieselnetz.ch/de/home/projekte-win/praxisprojekte/)                                                                                                                   |./_wissenschaft-externe-projekte/90-stiftung-wieselnetz-win-wiesel-patchw/90-stiftung-wieselnetz-win-wiesel-patchw.Rmd  |
|https://zhaw.maps.arcgis.com/apps/Viewer/index.html?webmap=403ac2f6e28f48fc9b954a3ea2648f21                                                                                  |./_wissenschaft-wiesel-co-projekte/51-lra/51-lra.Rmd                                                                    |

**Comment by ratnanil** [comment]
@wicoz: die Links sollten nun wieder funktionieren. Dies müssen wir v.a. testen wenn die webseite über wieselundco.ch läuft. Bis dahin schliesse ich diesen issue

**Comment by wicoz** [comment]
@ratnanil Dankeschön, das ist ein wichtiger task. 

Ich hoffe, mit der kleinen Reorg des Hauptmenus #29 ergeben sich dadurch wenige Anpassungen. 

So wie ich verstehe, kommt alles, was mit Links zu tun hat, hier rein? 
Shortlinks? verlinkte Dateien? Verweise auf Subsites oder andere websites?

**Comment by wicoz** [comment]
@ratnanil 
Bitte gib mir rasch Bescheid, ob es ok ist, dass ich folgende zT neuen (Short-)links in den Berichten verwende, die kurz vor dem Abschluss stehen: 

BESTEHEND
wieselundco.ch/news
www.wieselundco.ch/resultate

NEUE SHORTLINKS
www.wieselundco.ch/wuehlmaeuse  (http://www.wieselundco.ch/faszination-kleinraubtiere/wuehlmaeuse)
www.wieselundco.ch/bonus (http://www.wieselundco.ch/projekt/1-1-untersuetzung)
www.wieselundco.ch/asthaufen (http://wieselundco.ch/projekt/massnahmen/114-hinweise-haufen)
www.wieselundco.ch/winterquartier (http://www.wieselundco.ch/projekt/massnahmen/135-winterquartier)
www.wieselundco.ch/ansprechpersonen (http://wieselundco.ch/ueber-uns/27-die-traegerschaft-wir-stellen-uns-vor)

**Comment by wicoz** [comment]
@ratnanil Darüber hinaus gibt es in deiner Liste oben diverse fehlende Links, die auf Dokumente zugreifen, zT solche die mir sehr wichtig sind wie die Dossiers zu Wühlmäusen und Hecken. 

Kannst Du mir bitte sagen, wie Du zu obiger Liste gekommen bist? 
Sind das alle aus den Texten? 
Und entsprechend sind alle "extralinks", die man in joomla erstellen konnte (zB wie jener hier oben am Text http://wieselundco.ch/projekt/massnahmen/114-hinweise-haufen) vergessen gegangen? 

Bitte um Bescheid, dann kann ich die effizienter nachreichen.

**Comment by wicoz** [comment]
Die INTUITIV SICHTBARE Verlinkung ist bisher nicht toll. 
Du hast rückgemeldet, dass ein Button o.ä. auf fortführende Inhalte nicht möglich sind.

Wie heben wir die Links in den Beiträgen SICHTBAR hervor? 
Farblich wie bisher (dunkelorange) finde ich eine gute Option. Mit eckigen Klammern find ich nicht toll.

**Comment by ratnanil** [comment]
> Bitte gib mir rasch Bescheid, ob es ok ist, dass ich folgende zT neuen (Short-)links in den Berichten verwende, die kurz vor dem Abschluss stehen

Ja das ist ok

**Comment by ratnanil** [comment]
> Kannst Du mir bitte sagen, wie Du zu obiger Liste gekommen bist?

Das sind alle teile im text, welche die folgende Form aufweisen `[irgendein Text](url)`

**Comment by wicoz** [comment]
@ratnanil super, danke!
Beim gestrigen "fertigstellen" des Schlussbericht ist noch herausgekommen, dass folgende 2 shortlinks noch fehlen: 

NEU:
www.wieselundco.ch/presse
(www.wieselundco.ch/resultate/pressespiegel)

www.wieselundco.ch/feldscheunen
(http://www.wieselundco.ch/projekt/massnahmen/62-wir-unterstuetzen-die-instanstellung-von-feldscheunen)

Ich gehe davon aus, dass diese auch möglich sind. 
-> Kontrolle dann zuletzt - entsprechend Titel des issues angepasst

**Comment by ratnanil** [comment]
warten auf #6

**Comment by wicoz** [comment]
nach der Umleitung bitte shortlinks erstellen.

Achtung die Ursprungspfade stimmen durch Verschiebungen jetzt nicht mehr alle, solltest Du aber schnell finden können.

**Comment by ratnanil** [comment]
@wicoz; ich habe die shortlinks jetzt eingerichtet. Für einige braucht es keine Einstellungen, weil die Hierarchie der Website diesen "shortlink" direkt ergibt. Für andere braucht es ein `_redirects` file. Kannst du mal testen ob alles shortlinks unten erwähnt sind und ob alle funktionieren?

- www.wieselundco.ch/news *-> braucht kein redirect, ist "geschenkt"*
- www.wieselundco.ch/resultate *-> braucht kein redirect, ist g"eschenkt"*
- www.wieselundco.ch/wuehlmaeuse *-> braucht kein redirect, ist "geschenkt"*
- www.wieselundco.ch/bonus *-> braucht kein redirect, ist "geschenkt"*
- www.wieselundco.ch/asthaufen (redirect auf `projekt-massnahmen/114-hinweise-haufen/`)
- www.wieselundco.ch/winterquartier (redirect auf `/projekt-massnahmen/135-winterquartier/`)
- www.wieselundco.ch/ansprechpersonen (redirect auf `/ueber-uns/27-die-traegerschaft-wir-stellen-uns-vor/`)
- www.wieselundco.ch/presse (redirect auf `/projekt-resultate/pressespiegel/`)
- www.wieselundco.ch/feldscheunen (redirect auf `/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/`)

**Comment by wicoz** [comment]
Super Sache, dass die Page nun online ist und obige Shortlinks eingerichtet sind!!

Folgend noch offenes: 

wieselundco.ch/massnahmenkarte 
und 
wieselundco.ch/sichtungskarte
funktionieren nicht mehr.


Hab mir notiert, dass wieselundco.ch/projekt/massnahmen in WK Bericht vorkommt. 
Diese URL führt ins Leere. Im WK Bericht funktioniert momentan die Suchfunktion nicht, deshalb weiss ich nicht, wo dies vorkommt. Man kann den Link auch im WK Bericht anpassen.

**Comment by ratnanil** [comment]
> Hab mir notiert, dass wieselundco.ch/projekt/massnahmen in WK Bericht vorkommt.

werde das im wk bericht anpassen

**Comment by ratnanil** [comment]
> wieselundco.ch/massnahmenkarte
> und
> wieselundco.ch/sichtungskarte
> funktionieren nicht mehr.

Wohin sollen die verlinken? auf einen artikel oder direkt auf die zhaw / arcgis karten? kannst du mir ggf. die links nochmal geben?

**Comment by wicoz** [comment]
wieselundco.ch/massnahmenkarte  
-> http://gis.lsfm.zhaw.ch/portal/apps/webappviewer/index.html?id=07f55f0607b7403ba9b937a546d285eb


wieselundco.ch/sichtungskarte
-> http://gis.lsfm.zhaw.ch/portal/apps/webappviewer/index.html?id=ab36b8f1202244b7bdcc860e06be2270

**Comment by ratnanil** [comment]
beide weiterleitungen sind nun implementiert. Damit die ganzen shortlinks aus dem thread nicht zusammengesucht werden müssen platziere ich hier nochmal eine vollständige liste:


- www.wieselundco.ch/news *-> braucht kein redirect, ist "geschenkt"*
- www.wieselundco.ch/resultate *-> braucht kein redirect, ist g"eschenkt"*
- www.wieselundco.ch/wuehlmaeuse *-> braucht kein redirect, ist "geschenkt"*
- www.wieselundco.ch/bonus *-> braucht kein redirect, ist "geschenkt"*
- www.wieselundco.ch/asthaufen (redirect auf `projekt-massnahmen/114-hinweise-haufen/`)
- www.wieselundco.ch/winterquartier (redirect auf `/projekt-massnahmen/135-winterquartier/`)
- www.wieselundco.ch/ansprechpersonen (redirect auf `/ueber-uns/27-die-traegerschaft-wir-stellen-uns-vor/`)
- www.wieselundco.ch/presse (redirect auf `/projekt-resultate/pressespiegel/`)
- www.wieselundco.ch/feldscheunen (redirect auf `/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/`)
- www.wieselundco.ch/massnahmenkarte (redirect auf http://gis.lsfm.zhaw.ch/portal/apps/webappviewer/index.html?id=07f55f0607b7403ba9b937a546d285eb)
- www.wieselundco.ch/sichtungskarte (redirect auf http://gis.lsfm.zhaw.ch/portal/apps/webappviewer/index.html?id=ab36b8f1202244b7bdcc860e06be2270)

**Comment by wicoz** [comment]
Vielen Dank!

**Comment by ratnanil** [comment]
https://wieselundco.ch/wissenschaft

**Comment by wicoz** [comment]
Alle Shortlinks (redirects) funktionieren nicht!

Ich wollte den Newsletter eigentlich auf morgen Sonntag auslösen - aber ich finds kacke, Dinge zu verschicken, die nicht funktionieren.

Wann kannst Du dies wiederherstellen??

> beide weiterleitungen sind nun implementiert. Damit die ganzen shortlinks aus dem thread nicht zusammengesucht werden müssen platziere ich hier nochmal eine vollständige liste:
> * [www.wieselundco.ch/asthaufen](http://www.wieselundco.ch/asthaufen) (redirect auf `projekt-massnahmen/114-hinweise-haufen/`)
> * [www.wieselundco.ch/winterquartier](http://www.wieselundco.ch/winterquartier) (redirect auf `/projekt-massnahmen/135-winterquartier/`)
> * [www.wieselundco.ch/ansprechpersonen](http://www.wieselundco.ch/ansprechpersonen) (redirect auf `/ueber-uns/27-die-traegerschaft-wir-stellen-uns-vor/`)
> * [www.wieselundco.ch/presse](http://www.wieselundco.ch/presse) (redirect auf `/projekt-resultate/pressespiegel/`)
> * [www.wieselundco.ch/feldscheunen](http://www.wieselundco.ch/feldscheunen) (redirect auf `/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/`)
> * [www.wieselundco.ch/massnahmenkarte](http://www.wieselundco.ch/massnahmenkarte) (redirect auf http://gis.lsfm.zhaw.ch/portal/apps/webappviewer/index.html?id=07f55f0607b7403ba9b937a546d285eb)
> * [www.wieselundco.ch/sichtungskarte](http://www.wieselundco.ch/sichtungskarte) (redirect auf http://gis.lsfm.zhaw.ch/portal/apps/webappviewer/index.html?id=ab36b8f1202244b7bdcc860e06be2270)
