### ISSUE TITLE
übergeordnete Mitteilung "Projekt abgeschlossen"

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#15]
am besten wäre eine Mitteilung in der Kopfzeile (bisher Rubrikleiste). 
ZB ganz rechts, statt "Wiesel & Co am Zimmerberg" -> Logo und "2014 - 2021, Projekt abgeschlossen" oder nur mit den Jahreszahlen

oder

falls es irgendwelche Banner gibt, darin integrieren (das war mal der Plan)

**Comment by wicoz** [comment]
Im footer ist die Mitteilung nicht sinnvoll; sie muss oben stehen; jederzeit ersichtlich, aber nicht penetrant

**Comment by ratnanil** [comment]
kannst du mal die Eingangsseite anschauen https://wieselundco.github.io/website/, passt das so?

**Comment by ratnanil** [comment]
du kannst diesen issue wieder öffnen falls du noch handlungsbedarf siehst
