### ISSUE TITLE
Flüchtigkeitsfehler/ Rechtschreibung

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#16]
ich wär Dir dankbar, wenn ich mich um anderes kümmern könnte:

Wiesel und Co am Zimmeberg -> Wiesel & Co am Zimmerberg
(in Rubrikleiste und auf der Homepage)

Rubrikleiste Mitwirken und https://wieselundco.github.io/website/Beobachtung-Melden.html: 
Beobachtung Melden -> Beobachtung melden

**Comment by wicoz** [comment]
https://wieselundco.github.io/website/Ausgangslage-und-Ziele.html

Titel ohne Bindestriche

**Comment by ratnanil** [comment]
alle erledigt
