### ISSUE TITLE
Texte https://wieselundco.github.io/website/

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#17]
News -> Text ersetzen: 

Das Projekt Wiesel & Co am Zimmerberg war von 2014 bis 2021 aktiv. 
Viele der News sind auch heute noch interessant.

**Comment by ratnanil** [comment]
Kannst du noch genauer ausformulieren, wo dieser Text zu platzieren ist?

**Comment by ratnanil** [comment]
siehe #15

**Comment by ratnanil** [comment]
ist dieser issue mit der neuen startseite erledigt?

https://wieselundco.github.io/website/
