### ISSUE TITLE
Leserlichkeit Starttexte

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#18]
Die Leserlichkeit der Starttexte ist aufgrund fehlender Zeilenumbrüche, Absätze, Leerzeichen etc. nicht gegeben.

**Comment by ratnanil** [comment]
beispiel?

**Comment by wicoz** [comment]
Dazu braucht es eigentlich keine Beispiele, das ist überall ersichtlich, wenn Du alte und neue Website vergleichst. Es ist keine tiefe Priorität. 
Zur Leserlichkeit brauch es diese Absätze.

Nun ist es ja so, dass einige Texte angepasst werden (Zeitform, inhaltlich etc. ). Beide Anpassungen sollten also in einem gehen. 

Ich mache nun 1 Beispiel via "propose changes" im Artikel "Motivation". 
Bitte in diesem issue rückmelden, ob die Absätze dort angenommen werden. Dann mach ich dies überall so.

**Comment by wicoz** [comment]
wie ich aus der Editor-Ansicht (Bsp "Motivation") interpretiere, sind Textbausteine, die auf der nächsten Zeile beginnen, auf der Website nicht durch einen Zeilenumbruch markiert. 
Damit ein Absatz mit Leerzeile entsteht, brauch es zwei Leerzeilen im Editor. 
Ich richte mich nun danach - bitte Einstellungen nicht ändern.

**Comment by ratnanil** [comment]
>  Bitte in diesem issue rückmelden, ob die Absätze dort angenommen werden. Dann mach ich dies überall so.
> Damit ein Absatz mit Leerzeile entsteht, brauch es zwei Leerzeilen im Editor.

es brauch jeweils 1 Leerzeile, wobei die zeilen mit 1 Tab oder zwei Leerschlägen eingerückt beginnen müssen. 

vorher: 
![grafik](https://user-images.githubusercontent.com/12532091/127988685-414c9146-7881-4361-83df-b0c8e9f95650.png)

nachher: 

![grafik](https://user-images.githubusercontent.com/12532091/127988721-a82c7485-9cf2-4899-860c-3c00ffc50661.png)


siehe: https://wieselundco.github.io/website/projekt-ausgangslage/2-motivation/

**Comment by wicoz** [comment]
ok, beides scheint zu funktionieren, wenn ich in den Editor reinschaue:
entweder 1 Leerzeile + eingerückt oder 2 Leerzeilen.
*************************

www.wieselundco.ch


Stefan Keller, Projektleitung
Aeschstrasse 23 <https://wogeno-mogelsberg.clubdesk.com/>
9122 Mogelsberg <https://wogeno-mogelsberg.clubdesk.com/>
076 374 70 01
044 500 52 82


Am Di., 3. Aug. 2021 um 11:02 Uhr schrieb Nils ***@***.***>:

**Comment by ratnanil** [comment]
> ok, beides scheint zu funktionieren, wenn ich in den Editor reinschaue:
> entweder 1 Leerzeile + eingerückt oder 2 Leerzeilen.

Nein, die neuen Zeilen *müssen* eingerückt sein!

**Comment by wicoz** [comment]
Ist es so, dass neben den die Texte neben den Thumbnails (mit Starttexten hatte ich primär diese gemeint) gar keine Zeilenumbrüche und Absätze haben können?
Oder wie geht das?
Ich finde das nach wie vor für die Leserlichkeit sehr wichtig. 

Mittlerweile habe ich gemerkt, dass ein Einrücken mit tab, den eingerückten Text im Editor in grauer Schrift zeigt. (dies hab ich nun nachträglich vorgenommen von oben in der Resultate-Beitragsliste (code) bis und mit Beitrag Gesamtschau WK ) 
Ob das das Signal für einen Absatz/Zeilenumbruch in der Website-Darstellung ist? 

Blackbox für mich... 
bitte klären

**Comment by ratnanil** [comment]
> Ist es so, dass neben den die Texte neben den Thumbnails (mit Starttexten hatte ich primär diese gemeint) gar keine Zeilenumbrüche und Absätze haben können?

ja, so wie ich das sehe sind dort keine Zeilenumbrüche und Absätze möglich.. (ein screenshot hätte dies frage viel früher geklärt)

> Mittlerweile habe ich gemerkt, dass ein Einrücken mit tab, den eingerückten Text im Editor in grauer Schrift zeigt. (dies hab ich nun nachträglich vorgenommen von oben in der Resultate-Beitragsliste (code) bis und mit Beitrag Gesamtschau WK )

Muss ich da noch was machen? Und was meinst du mit "(code)"?

>  Ob das das Signal für einen Absatz/Zeilenumbruch in der Website-Darstellung ist?

Nein das ist eher zufall
