### ISSUE TITLE
https://wieselundco.github.io/website/News.html

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#19]
neuer Eintrag, Datum heute

Titel:
Viel Glück auf der Wieselpirsch!

Text: (inkl. Zeilenumbrüche!)
Sichtungen von Wiesel & Co brauchen etwas Glück. 
Aufgrund ihrer Kurzlebigkeit und ihrem besonderen Aktivitätsrhythmus sind gezielte Beobachtungen dieser Tierarten schwierig.
Dennoch lohnt sich eine [Pirsch, wenn sie auf den beschriebenen Wegen gehen] und die Sinne schärfen! 
Die Zwei-Seeli-Tour (Zwei-Seeli-Tour mit https://map.wanderland.ch/?lang=de&p=&route=all&photos=yes&logo=yes&season=summer&resolution=2.15&E=2692342&N=1226467&bgLayer=pk&layers=Wanderland%2CStation&trackId=6665128 verlinken) führt durch die Hügellandschaft zwischen Hütten, Schönenberg und Samstagern.

DATEIEN ZU VERLINKEN
![BirdLifeZürich-WieselWanderung20_snip](https://user-images.githubusercontent.com/49158554/123140238-5946fd80-d457-11eb-9dc2-94d25aa5230e.jpg) jpg neben Text 
[BirdLifeZürich-Wieselpirsch.pdf](https://github.com/wieselundco/website/files/6703798/BirdLifeZurich-Wieselpirsch.pdf)  pdf verlinken hinter [....] und Bild

**Comment by ratnanil** [comment]
sieht jetzt nicht genau so aus wie gewünscht, aber kannst du damit leben? Du kannst den Artikel auch hier ein stückweit bearbeiten: 
https://github.com/wieselundco/website/edit/master/_news/2021-06-24-viel-glck-auf-der-wieselpirsch/viel-glck-auf-der-wieselpirsch.Rmd

**Comment by wicoz** [comment]
Bitte hochformatiges Bild einsetzen, das ich extra erstellt hatte und im Ursprungsbeitrag drin ist. 

Bitte darauf achten, dass alle links auf externe Seiten in neuem Fenster öffnen. 
Hier bei "Zwei-Seeli-Tour" anpassen. 

Absätze und Flüchtigkeitsfehler habe ich im Editor korrigiert.

**Comment by ratnanil** [comment]
> Bitte hochformatiges Bild einsetzen, das ich extra erstellt hatte und im Ursprungsbeitrag drin ist. 

ersetzt. Im introbild würde ich das breite gerne behalten, passt das so?

> Bitte darauf achten, dass alle links auf externe Seiten in neuem Fenster öffnen. 
Hier bei "Zwei-Seeli-Tour" anpassen. 

ist ein neuer issue: #35

**Comment by wicoz** [comment]
danke

> Im introbild würde ich das breite gerne behalten, passt das so?
beide sind hochformatig und ich finde das sieht auf dem desktop bestens aus
