### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#21]
von oben nach unten: 

ich sehe ein Bild Icon aber kein Bild; ein wechselnder Bildbanner wie bis anhin oder zumindest eines der Bilder (zB das mit dem Iltis http://wieselundco.ch/images/headers/banner_v2//litis1.jpg ) wäre sehr toll, da es zum Besuch der Website einladen wirkt. 

Der ausgeschriebene Titel ist nicht angebracht, da gleich drunter dasselbe im Logo steht. Im Iltis Bild finde ich es ok

Das Logo lieber noch grösser. 
Oder - wenn oben http://wieselundco.ch/images/headers/banner_v2//litis1.jpg, dann vielleicht besser Grösse belassen und eher unterhalb Text platzieren. 

Text korrigieren und ev. etwas grössere Schrift: 

Das Projekt im Bezirk Horgen ZH war von 2014 bis 2021 aktiv. 
*Zeilenumbruch*
Unser Knowhow stellen wir gerne zur Verfügung.

**Comment by ratnanil** [comment]
hast du noch die ganzen Logovarianten noch irgendwo?

**Comment by wicoz** [comment]
Ich denke, die ersten beiden haben die richtige Dateigrösse - sag mir, wenn Du was bestimmtes suchst.

jpg:
![Wiesel_Logo_RGB_zugeschnitten_920px](https://user-images.githubusercontent.com/49158554/128407118-85b9bf98-db95-47c7-97c2-b9258bd74b1d.jpg)
und transparent (png):
![Wiesel_Logo_RGB](https://user-images.githubusercontent.com/49158554/128407176-ab585761-9ee9-45c7-aecc-a5592fdda029.png)


kleinere files:

![Wiesel_Logo_Cmyk_claim_zugeschn_druck](https://user-images.githubusercontent.com/49158554/128406900-43fce3ef-7bec-40b8-ad23-7f339d5b7254.jpg)
![Wiesel_Logo_Cmyk_claim_ohneBeschn_druck_red](https://user-images.githubusercontent.com/49158554/128406930-ae968b1e-791f-4352-9884-99a247d777fd.jpg)

**Comment by wicoz** [comment]
Hab die Homepage noch mit Carmen angeschaut im Wissen, dass Du noch nicht fertig bist: 
Sie findet die Erscheinung momentan sehr lustlos (ich auch). 

Vorschlag: 
offizielles Logo ganz nach unten nehmen.

Oben http://wieselundco.ch/images/headers/banner_v2//litis1.jpg

In der Mitte der Text wie bisher:

Das Projekt im Bezirk Horgen ZH war von 2014 bis 2021 aktiv.
Zeilenumbruch
Unser Knowhow stellen wir gerne zur Verfügung.

Ich hoffe, so kommt mehr Lust auf zum reinschauen (bzw. die 3 Menu-Striche suchen).

Für die Leserlichkeit störend ist auch #37

**Comment by ratnanil** [comment]
dummerweise *muss* ich einen Titel haben, naheliegend wäre "Wiesel & Co am Zimmerberg". Deshalb passt der Iltis banner nicht wirklich, weil dort nochmals der Name drin steht. Können wir kein anderes Tierbild (ohne Text) verwenden? Z.B. so:

![image](https://user-images.githubusercontent.com/12532091/128518782-732ead87-de08-46a4-b281-6d23e9361f87.png)

**Comment by wicoz** [comment]
Wunderbar!!
copyright vom Foto ist ok?

**Comment by ratnanil** [comment]
wollte mich um copyright kümmern nach deinem ok. hab die quelle nicht gefunden und deshalb ein anderes bild genommen, von flicker mit cc lizenz. so ok?

**Comment by wicoz** [comment]
Bitte tauschen mit folgendem.
Foto: Susanne Heusser
![D90_20140605_41549-snip](https://user-images.githubusercontent.com/49158554/128779892-9b2bafca-513e-4ecc-b32b-5f3f08b461f1.jpg)

**Comment by ratnanil** [comment]
erledigt

**Comment by wicoz** [comment]
sehr schön
