### ISSUE TITLE
Datumspalte

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#22]
Ich nutzte die Daten zum Sortieren der Beiträge, die Daten waren ja bisher nirgends sichtbar. Daher ist die Datumspalte links auf den meisten Subsites irreführend. 

Auf der News-Site und der Resultate-Site sind die Daten so wie sichtbar durchaus erwünscht, ja nützlich. 

-> gerne nur auf diesen Sites sichtbar lassen
-> wenn dies nicht möglich ist, überall ausblenden

**Comment by ratnanil** [comment]
https://github.com/rstudio/distill/issues/394

**Comment by ratnanil** [comment]
kann man vermutlich nicht entfernen. ich eröffne diesen issue wieder, wenn ich eine andersweitige antwort habe (siehe letzter link)

**Comment by ratnanil** [comment]
hab dafür doch noch eine Lösung gefunden! Datum wird nur noch auf News und resultate angezeigt

**Comment by ratnanil** [comment]
@wicoz

**Comment by wicoz** [comment]
mega guet! danke!!
