### ISSUE TITLE
Partner: Links

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#24]
Unter http://wieselundco.ch/ueber-uns/7-partner war jeder Partner und Geldgeber verlinkt. 
wär schon chic, Du musst sie "nur" kopieren : )

**Comment by ratnanil** [comment]
dafür möchte ich lieber keine zeit mehr investieren

**Comment by ratnanil** [comment]
falls du dies anpackst, bitte https://github.com/wieselundco/website/issues/35#issuecomment-892542660 beachten

**Comment by wicoz** [comment]
haben meine Anpassungen im code gefruchtet? 

<a href="http://www.lotteriefonds.zh.ch/" target="_blank">Lotteriefonds Kanton Zürich</a>
<a href="http://www.fls-fsp.ch/" target="_blank">Fonds Landschaft Schweiz</a>
<a href="http://www.ernst-goehner-stiftung.ch/index.php/de" target="_blank">Ernst Goehner Stiftung</a>
<a href="http://temperatio.ch/" target="_blank">Temperatio Stiftung</a>

<a href="http://www.paul-schiller-stiftung.ch/" target="_blank">Paul Schiller Stiftung</a>
<a href="http://www.horgen.ch/" target="_blank">Gemeinde Horgen</a>
<a href="http://www.kilchberg.ch/" target="_blank">Gemeinde Kilchberg</a>
<a href="http://www.langnauamalbis.ch/" target="_blank">Gemeinde Langnau a.A.</a>
<a href="http://www.richterswil.ch/" target="_blank">Gemeinde Richterswil</a>
<a href="http://www.thalwil.ch/" target="_blank">Gemeinde Thalwil</a>
<a href="http://www.waedenswil.ch/" target="_blank">Gemeinde Wädenswil</a>
<a href="http://www.wieselnetz.ch/" target="_blank">Stiftung Wieselnetz</a>
<a href="http://www.wls.ch/" target="_blank">WLS WildLife Solutions</a>

<a href="https://aln.zh.ch/internet/baudirektion/aln/de/naturschutz.html" target="_blank">Fachstelle Naturschutz Kanton Zürich</a>
<a href="http://www.nv-schoenenberg.ch/" target="_blank">Fachstelle Naturschutz Kanton Zürich</a>
<a href="https://www.birdlife-zuerich.ch/home/" target="_blank">BirdLife Zürich</a>
<a href="http://www.lsfm.zhaw.ch/de/science/institute-zentren/iunr-integrativeoekologie/geoinformatik.html" target="_blank">Forschungsgruppen Geoinformatik und Wildtiermanagement der ZHAW Wädenswil</a>
<a href="http://www.cscf.ch/" target="_blank"> Centre Suisse de Cartographie de la Faune</a>
<a href="http://www.cashctrl.com/de/" target="_blank">Die Schweizer Online Buchhaltung
mit FREE Version.</a>
<a href="https://wildnispark.ch/" target="_blank"> Stiftung Wildnispark Zürich</a>

<a href="https://dokumentarfilme.ch" target="_blank">www.dokumentarfilme.ch</a>
<a href="http://www.syndrega.ch/" target="_blank">Syndrega GmbH</a>
<a href="http://www.illustrat.ch/" target="_blank">Illustrat, Atelier für Grafik und Illustration</a>

<a href="http://www.schluchtalhof.ch/" target="_blank">Werner und Karin Fankhauser, Schluchtalhof Wädenswil</a>
<a href="https://www.stallstreuli.ch/" target="_blank">Streuli Aktivstall, Horgenberg</a>
<a href="http://www.hintermannweber.ch/" target="_blank">Hintermann Weber</a>

**Comment by ratnanil** [comment]
danke für die arbeit. mit etwas anpassung hat es geklappt

https://wieselundco.netlify.app/ueber-uns/7-partner/

**Comment by wicoz** [comment]
ZHAW Link im Code korrigiert, der alte war tot. 
https://www.zhaw.ch/de/lsfm/institute-zentren/iunr/ecosystems-and-biodiversity/

**Comment by ratnanil** [comment]
der link ist m.E. auf der webseite aktualisiert

**Comment by wicoz** [comment]
Die Links öffnen ja alle im gleichen Fenster, statt in einem neuen.
Dies konnte ich nicht korrigieren, weil es hier eine spezielle Schreibweise im rmd gibt .
Ev. kannst Du das einfach anpassen?

**Comment by wicoz** [comment]
dann haben ja Harald Cigler und die Jagdgesellschaft Bocken keine Website. 
Die Verlinkung auf die Ursprungsseite ist unnötig und verwirrend. 
Bitte Link aufheben.

**Comment by ratnanil** [comment]
das ist jetzt eines dieser kleinen details, mit denen wir leben müssen
