### ISSUE TITLE
Assignees?

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#26]
Ist es überhaupt nötig bzw. sinnvoll, dies anzuwählen, oder ist es eher hinderlich, wenn man das umstellen vergisst? 

Wie machst Du es, dass die Meldungen zuverlässig beim Adressaten ankommen?

**Comment by ratnanil** [comment]
> Ist es überhaupt nötig bzw. sinnvoll, dies anzuwählen, oder ist es eher hinderlich, wenn man das umstellen vergisst?

ich finde es sinnvoll, mit assignees zu arbeiten weil dabei immer explizit ist, wer mit dem issue am zug ist. Wenn man [seine eigenen issues](is:open is:issue author:@me ) durchgeht sieht man dann ja, wenn man einen issue "umstellen" muss.


> Wie machst Du es, dass die Meldungen zuverlässig beim Adressaten ankommen?

wenn ich dich "assigne" gehe ich davon aus das du eine Mitteilung bekommst. Ich habe allerdings alle meldungen auf der seite abonniert, siehe hier:

![grafik](https://user-images.githubusercontent.com/12532091/127993662-71db2575-fb92-4cd3-b351-c846e621492c.png)

**Comment by wicoz** [comment]
merci!
