### ISSUE TITLE
Kopfzeile

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#27]
es ging ja noch darum, sichtbar zu machen, dass das Projekt beendet ist, egal auf welcher subsite.

in der Kopfleiste steht links der Projektname und daneben Home. 
Beides führt zum gleichen Ziel. 

Bitte statt "Home" "2014 - 2021" schreiben.

**Comment by ratnanil** [comment]
gegenvorschlag:

![grafik](https://user-images.githubusercontent.com/12532091/128000360-6b0fe541-d095-4708-ac44-d468e8e7379c.png)

**Comment by wicoz** [comment]
very nice
