### ISSUE TITLE
Sichtbarkeit Menu-Striche verbessern

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#28]
Wenn man auf die Homepage geht, fehlt das Menu in der Kopfzeile, auch die 3 Striche, die oft stellvertretend dafür stehen.

**Comment by ratnanil** [comment]
![Screenshot_20210803-113336_Firefox](https://user-images.githubusercontent.com/12532091/127993462-bcd7855a-fe3b-4adf-adac-5d034610f76c.jpg)
![Screenshot_20210803-113331_Firefox](https://user-images.githubusercontent.com/12532091/127993473-bd7d3456-5258-446a-ab75-3e055b3cc734.jpg)

**Comment by ratnanil** [comment]
ich sehe die striche und bei mir ist es responsive.. wie sieht es denn bei dir aus?

**Comment by wicoz** [comment]
hmm, bei mir nicht. Samsung S7, android
wenn ich auf die Kopfzeile tippe, dann flackert ganz kurz die Suchfunktion auf. 
Ansonsten ist nur der Homepage Link zu sehen.
Kein Weiterkommen.
![2021-08-03 14 39 47](https://user-images.githubusercontent.com/49158554/128017310-9f9eecc0-a5cb-4745-9a09-6a4d249d0b4e.jpg)

**Comment by ratnanil** [comment]
ich denke das hat mit deinem browser was zu tun.. kannst du es mal mit einem anderen browser auf den handy testen? ich kann da nicht viel machen, die site ist responsive gebaut..

**Comment by wicoz** [comment]
ich nutze chrome und hatte noch nie ein solches Problem festgestellt. 

beim öffnen mit dem Samsung Internet Browser genau dasselbe. 

Klar, mein Telefon ist nicht das neuste aber das geht andern Leute auch so. 
kannst Du das Problem mal in die github community schreiben, bitte?

![2021-08-04 10 12 09](https://user-images.githubusercontent.com/49158554/128146647-984bca96-b632-4bd7-a49f-c285a63356eb.jpg)

**Comment by ratnanil** [comment]
>  kannst Du das Problem mal in die github community schreiben, bitte?

nein tut mir leid, dafür fehlt mir die Kapazität

**Comment by wicoz** [comment]
> Wenn man auf die Homepage geht, fehlt das Menu in der Kopfzeile, auch die 3 Striche, die oft stellvertretend dafür stehen.
Carmen hat die 3 Menu-Striche auf den zweiten Blick entdeckt und ich nun auch. Hattest Du die Striche gesehen auf den obigen screenshots.... ?

Ich hoffe es gibt eine Möglichkeit, diese grösser zu machen UND/ODER farblich (zB WiCoZ-grün) hervorzuheben?
(Dieser Punkt liegt also nicht an der responsiveness sondern daran, dass Otto-Normalverbraucher momentan die 3-Striche nicht findet und damit die ganzen Inhalte (unsere Arbeit) nicht nutzen kann.)

**Comment by ratnanil** [comment]
so?

![image](https://user-images.githubusercontent.com/12532091/128513860-bc164133-3afb-43ae-885d-cf5a7d2b26f8.png)

**Comment by wicoz** [comment]
danke für den Versuch - auf dem Desktop orange bzw. wenn cursor drauf weiss - wunderbar!

Unglaublich: auf dem smartphone nach wie vor grau - trotz mehrmaligen refreshen!

![2021-08-07 17 39 21](https://user-images.githubusercontent.com/49158554/128605742-1c524294-a4a7-42ae-9390-da2bc78aa6a8.jpg)
![2021-08-07 17 39 33](https://user-images.githubusercontent.com/49158554/128605743-98033f88-57fb-4c0d-9dee-43fc5f359d97.jpg)
![2021-08-07 17 39 10](https://user-images.githubusercontent.com/49158554/128605744-6725be0e-3a7d-4c89-a87c-47cdb096d78f.jpg)

**Comment by ratnanil** [comment]
Bei mir auf dem handy sieht es so aus:

![Screenshot_20210808-183809_Firefox](https://user-images.githubusercontent.com/12532091/128639098-e469d48d-2c76-45e9-bec3-92757460a0ef.jpg)

**Comment by ratnanil** [comment]
ich bin mut meinem latein am ende

**Comment by ratnanil** [comment]
ich kann hier nichts mehr machen und schliesse deshalb das issue

**Comment by wicoz** [comment]
Danke für Deine Bemühungen. 
Grösser kann man die Menustriche also auch nicht machen?

Ich kann's echt nicht glauben, dass der Zugang zu einer Website (auf kleinem Bildschirm / Mobile) so ausfällt ; (

**Comment by ratnanil** [comment]
![threema-20210810-062944174](https://user-images.githubusercontent.com/12532091/129111812-6b97597f-5b56-450d-a394-fd70ba6e1d8f.png)
![image-20211008-072555](https://user-images.githubusercontent.com/12532091/129111842-58600f3e-a274-4cfa-9928-b569c75eb241.jpeg)

**Comment by ratnanil** [comment]
ich habe noch in meinem umfeld gefragt ob sie mir screenshots von der website schicken können.. die meisten sehen es so wie ich (siehe beispiele oben). wie gesagt, ich kann das problem nicht lösen
