### ISSUE TITLE
Reorganisation Hauptmenu

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#29]
...nur eine kleine Reorg, keine Sorge ; )

Kannst Du ohne grosse Umstände folgendes ändern? 

Mitwirken umbenennen in Förderung

Welche Massnahmen? von Projekt nach Förderung zügeln; dort zuoberst. 

Bitte dies bald vornehmen, damit ich in der Folge Querverlinkungen, Subsites und Inhalte anpassen kann.

**Comment by wicoz** [comment]
@ratnanil 
Wie kann ich allg. die Reihenfolge von Beiträgen in einer Rubrik ändern?
wie bisher übers Datum? 

Konkret: 
hier https://wieselundco.github.io/website/Welche-Massnahmen.html bitte diesen Beitrag zuunterst anordnen: 
https://wieselundco.github.io/website/projekt-massnahmen/59-welche-massnahmen-nuetzen-den-kleinra/

**Comment by ratnanil** [comment]
> Mitwirken umbenennen in Förderung
>Welche Massnahmen? von Projekt nach Förderung zügeln; dort zuoberst.

erledigt


> Bitte dies bald vornehmen, damit ich in der Folge Querverlinkungen, Subsites und Inhalte anpassen kann.

wie machst du querverlinkungen?

**Comment by wicoz** [comment]
@ratnanil super, danke!

> wie machst du querverlinkungen?
technisch: weiss noch nicht ; ) copypaste nach funktionierenden Beispielen vielleicht... 
ich meine Verweis auf andere Subsites. Dies machen mehr Sinn, nach einer Reorg.
