### ISSUE TITLE
Bilder-Gallerien durchschauen

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/website#3]
- [x] ./_faszination-kleinraubtiere-wuehlmaeuse/117-info-dossier-und-workshop-2/117-info-dossier-und-workshop-2.Rmd (fotos/Wuehlmaus-Workshops_17-19)
- [x] ./_mithelfen-anpacken-mithelfen/108-wieselwerk-mit-schulklassen/108-wieselwerk-mit-schulklassen.Rmd (fotos/WieselwerkeBis17-18)
- [x] ./_news/2014-01-29-16-exkursion-kleinraubtiere-ke/2014-01-29-16-exkursion-kleinraubtiere-ke.Rmd (fotos/2013_10_11_Exkursion)
- [x] ./_news/2016-01-29-69-souvenir-helferessen/2016-01-29-69-souvenir-helferessen.Rmd (fotos/2015_07_03_Helferessen)
- [x] ./_news/2017-01-30-79-hecken-und-waldrandpflegeku/2017-01-30-79-hecken-und-waldrandpflegeku.Rmd (fotos/Heckenkurs_20170125)
- [x] ./_news/2017-02-15-81-aktionstage-februar-2017/2017-02-15-81-aktionstage-februar-2017.Rmd (fotos/Aktionstage_Winter_2015_6/Moos_Ausee_Feb2017)
- [x] ./_projekt-massnahmen/107-hecken-und-waldrandaufwertungen/107-hecken-und-waldrandaufwertungen.Rmd (Workshops_Kurstage/Heckenpflege/Album-Heckenpflege)
- [x] ./_projekt-massnahmen/135-winterquartier/135-winterquartier.Rmd (bilder/Winterquartiere)
- [x] ./_projekt-resultate/101-feldscheunen-sanierung-2017-10/101-feldscheunen-sanierung-2017-10.Rmd (fotos/Feldscheunen/Sanierungen/Hinterberg2016_7/2017-10-22)
- [x] ./_projekt-resultate/110-feldscheunen-sanierung-2018-03/110-feldscheunen-sanierung-2018-03.Rmd (fotos/Feldscheunen/Sanierungen/Steinweid/Maerz2018/Album)
- [x] ./_projekt-resultate/112-beispiel-mosli/112-beispiel-mosli.Rmd (fotos/Fotofallenbilder/Mosli)
- [x] ./_projekt-resultate/120-drei-streuhuetten-sind-saniert/120-drei-streuhuetten-sind-saniert.Rmd (fotos/Feldscheunen/Sanierungen/chronik_Steinweid_Hinterberg_Chaltenboden)
- [x] ./_projekt-resultate/124-souvenir-dez-2019/124-souvenir-dez-2019.Rmd (fotos/Aktionstage_Dez_2019)
- [x] ./_projekt-resultate/125-wk-etappe1/125-wk-etappe1.Rmd (fotos/Fotofallenbilder/systematische-WK_Etappe1)
- [x] ./_projekt-resultate/133-erste-mast-strukturen/133-erste-mast-strukturen.Rmd (bilder/Gross-Struktur)
- [x] ./_projekt-resultate/134-acht-streuhuetten-saniert/134-acht-streuhuetten-saniert.Rmd (fotos/Feldscheunen/Sanierungen/Seeli-Chrutzelen)
- [x] ./_projekt-resultate/77-100-massnahmen-realisiert/77-100-massnahmen-realisiert.Rmd (fotos/Aktionstage_Winter_2015_6)
- [x] ./_projekt-resultate/94-feldscheunen-sanierung-2016-7/94-feldscheunen-sanierung-2016-7.Rmd (fotos/Feldscheunen/Sanierungen/Hinterberg2016_7)
- [x] ./_projekt-resultate/97-souvenir-2016-7/97-souvenir-2016-7.Rmd (fotos/Saison_2016_7)

**Comment by ratnanil** [comment]
```{r, echo = FALSE}
library(tidyverse)
list.files(path = "gallery", pattern = ".jpg$",full.names = TRUE) %>%
  tibble(src = .) %>%
  gallerier::lightbox_gallery("source", width = 200, display = TRUE)
```

**Comment by ratnanil** [comment]
- [ ]  {gallery}fotos/Wuehlmaus-Workshops_17-19{/gallery}
- [ ]  {gallery}fotos/WieselwerkeBis17-18{/gallery}
- [ ]  {gallery}fotos/2013\_10\_11\_Exkursion{/gallery}
- [ ]  {gallery}fotos/2015\_07\_03\_Helferessen{/gallery}
- [ ]  {gallery}fotos/Heckenkurs\_20170125{/gallery}<span
- [ ]  {gallery}fotos/Aktionstage\_Winter\_2015\_6/Moos\_Ausee\_Feb2017{/gallery}
- [ ]  {gallery}Workshops\_Kurstage/Heckenpflege/Album-Heckenpflege{/gallery}
- [ ]  {gallery}bilder/Winterquartiere{/gallery}
- [ ]  {gallery}fotos/Feldscheunen/Sanierungen/Hinterberg2016\_7/2017-10-22{/gallery}
- [ ]  {gallery}fotos/Feldscheunen/Sanierungen/Steinweid/Maerz2018/Album{/gallery}
- [ ]  {gallery}fotos/Fotofallenbilder/Mosli{/gallery}
- [ ]  {gallery}fotos/Feldscheunen/Sanierungen/chronik\_Steinweid\_Hinterberg\_Chaltenboden{/gallery}
- [ ]  {gallery}fotos/Aktionstage\_Dez\_2019{/gallery}
- [ ]  style="font-size: 12.16px;">{gallery}fotos/Fotofallenbilder/systematische-WK\_Etappe1{/gallery}</span>
- [ ]   {gallery}bilder/Gross-Struktur{/gallery}
- [ ]  {gallery}fotos/Feldscheunen/Sanierungen/Seeli-Chrutzelen{/gallery}
- [ ]  {gallery}fotos/Aktionstage\_Winter\_2015\_6{/gallery}
- [ ]  {gallery}fotos/Feldscheunen/Sanierungen/Hinterberg2016\_7{/gallery}
- [ ]  {gallery}fotos/Saison\_2016\_7{/gallery}
> cat(paste("- [ ]", images), sep = "\n")
- [ ] 
- [ ] 
- [ ] {gallery}fotos/2013\_10\_11\_Exkursion{/gallery}
- [ ] {gallery}fotos/2015\_07\_03\_Helferessen{/gallery}
- [ ] {gallery}fotos/Heckenkurs\_20170125{/gallery}<span
- [ ] {gallery}fotos/Aktionstage\_Winter\_2015\_6/Moos\_Ausee\_Feb2017{/gallery}
- [ ] {gallery}Workshops\_Kurstage/Heckenpflege/Album-Heckenpflege{/gallery}
- [ ] {gallery}bilder/Winterquartiere{/gallery}
- [ ] {gallery}fotos/Feldscheunen/Sanierungen/Hinterberg2016\_7/2017-10-22{/gallery}
- [ ] {gallery}fotos/Feldscheunen/Sanierungen/Steinweid/Maerz2018/Album{/gallery}
- [ ] {gallery}fotos/Fotofallenbilder/Mosli{/gallery}
- [ ] {gallery}fotos/Feldscheunen/Sanierungen/chronik\_Steinweid\_Hinterberg\_Chaltenboden{/gallery}
- [ ] {gallery}fotos/Aktionstage\_Dez\_2019{/gallery}
- [ ] style="font-size: 12.16px;">{gallery}fotos/Fotofallenbilder/systematische-WK\_Etappe1{/gallery}</span>
- [ ]  {gallery}bilder/Gross-Struktur{/gallery}
- [ ] {gallery}fotos/Feldscheunen/Sanierungen/Seeli-Chrutzelen{/gallery}
- [ ] {gallery}fotos/Aktionstage\_Winter\_2015\_6{/gallery}
- [ ] {gallery}fotos/Feldscheunen/Sanierungen/Hinterberg2016\_7{/gallery}
- [ ] {gallery}fotos/Saison\_2016\_7{/gallery}

**Comment by ratnanil** [comment]
Hallo Stefan,

Die Galerien habe ich nun ersetzt. Du kannst diese hier anschauen und bei Bedarf "abhaken".

Auf die Bilder Reihenfolge habe ich jetzt nicht geschaut.. wenn die nicht stimmen sollte, kannst du dich in diesem Issue melden.

- [ ] https://wieselundco.github.io/website/faszination-kleinraubtiere-wuehlmaeuse/117-info-dossier-und-workshop-2
- [ ] https://wieselundco.github.io/website/mithelfen-anpacken-mithelfen/108-wieselwerk-mit-schulklassen
- [ ] https://wieselundco.github.io/website/news/2014-01-29-16-exkursion-kleinraubtiere-ke
- [ ] https://wieselundco.github.io/website/news/2016-01-29-69-souvenir-helferessen
- [ ] https://wieselundco.github.io/website/news/2017-01-30-79-hecken-und-waldrandpflegeku
- [ ] https://wieselundco.github.io/website/news/2017-02-15-81-aktionstage-februar-2017
- [ ] https://wieselundco.github.io/website/projekt-massnahmen/107-hecken-und-waldrandaufwertungen
- [ ] https://wieselundco.github.io/website/projekt-massnahmen/135-winterquartier
- [ ] https://wieselundco.github.io/website/projekt-resultate/101-feldscheunen-sanierung-2017-10
- [ ] https://wieselundco.github.io/website/projekt-resultate/110-feldscheunen-sanierung-2018-03
- [ ] https://wieselundco.github.io/website/projekt-resultate/112-beispiel-mosli
- [ ] https://wieselundco.github.io/website/projekt-resultate/120-drei-streuhuetten-sind-saniert
- [ ] https://wieselundco.github.io/website/projekt-resultate/124-souvenir-dez-2019
- [ ] https://wieselundco.github.io/website/projekt-resultate/125-wk-etappe1
- [ ] https://wieselundco.github.io/website/projekt-resultate/133-erste-mast-strukturen
- [ ] https://wieselundco.github.io/website/projekt-resultate/134-acht-streuhuetten-saniert
- [ ] https://wieselundco.github.io/website/projekt-resultate/77-100-massnahmen-realisiert
- [ ] https://wieselundco.github.io/website/projekt-resultate/94-feldscheunen-sanierung-2016-7
- [ ] https://wieselundco.github.io/website/projekt-resultate/97-souvenir-2016-7

**Comment by wicoz** [comment]
dankeschön, fickr funktioniert bei mir am desktop schön, schnelle Reaktionszeit und alles. 

sehr "responsive" ist das Ganze allerdings leider nicht, der erhoffte Mehrwert aus der Migration klein. 
Denn wenn man sich die Site auf dem smartphone anschaut, dann ist die Handhabung mässig; mit dem Wechsel auf flickr etwas besser. 

Was die Reihenfolgen angeht, nehme ich mir ein andermal Zeit - issue offen lassen.

**Comment by ratnanil** [comment]
> sehr "responsive" ist das Ganze allerdings leider nicht, der erhoffte Mehrwert aus der Migration klein.

der Grund für die Migration war nie die responsiveness.

>  Denn wenn man sich die Site auf dem smartphone anschaut, dann ist die Handhabung mässig; mit dem Wechsel auf flickr etwas besser.

wenn man auf die jeweiligen alben auf flicker.com anschaut, sind diese sehr responsive. Allenfalls können wir ergänzend zum einbinden der alben auch auf die alben selbst auf flicker verlinken. Allerdings gelangt man auch selbst dorthin, wenn man auf 

also auf https://wieselundco.github.io/website/projekt-resultate/97-souvenir-2016-7/

auf diesen link klicken: 

![grafik](https://user-images.githubusercontent.com/12532091/127983560-eddfb5c4-e29e-47f0-8255-8bde02087a43.png)

gelangt man hierhin: https://www.flickr.com/photos/193617721@N08/albums/72157719611415557

**Comment by wicoz** [comment]
@ratnanil  passt gut, Nils, die Lösung mit flickr. Danke!
Es braucht keine zusätzlichen Links/Einbindung aus meiner Sicht.

Die Reihenfolge der Bilder dünkt mich schon recht im Argen, muss mir dies allerdings nochmals in Ruhe anschauen. 
Wie soll diese Rückmeldung laufen, damit die Aufwände zum gewünschten Ziel kommen? 
Oder: Wie läuft die Sortierung auf flickr?

**Comment by ratnanil** [comment]
folgendermassen können alben auf Flickr sortiert werden:

1. auf https://www.flickr.com einloggen (username: gmail adresse, passwort: 2x gmail passwort hintereinander)
2. gewünschtes Album öffnen
3. klick auf "In Organizr bearbeiten"
4. klick auf *Anordnen -> Alphabetisch*
5. klick auf "speichern

**Comment by wicoz** [comment]
d.h. ich habe username & passwort nicht und kann das nicht selber editieren?

**Comment by ratnanil** [comment]
username und pw per threema geschickt

**Comment by wicoz** [comment]
Gallerie unter https://wieselundco.github.io/website/wissenschaft-externe-projekte/126-mammaliabox/ fehlt noch - hast Du eine gute Vorgehensweise, die Bilder nach flickr zu ziehen?

**Comment by wicoz** [comment]
Auch diese Bilder fehlen noch auf der neuen Website http://www.wieselundco.ch/faszination-kleinraubtiere/unsere-leitarten/13-die-familie-der-marderartigen

**Comment by wicoz** [comment]
Habe die Gallerien aus den beiden letzten Kommentaren erstellt und die vorherigen geordnet.
