### ISSUE TITLE
Neuer Beitrag: Pressespiegel

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#30]
@ratnanil 
Bitte erstellen, damit ich diesen später ergänzen kann. 

Rubrik: News und Resultate (geht dies bei github auch?)
Titel: Pressespiegel
Datum: 20.6.21

Vorläufiger Starttext: 
Die Aktivitäten von Wiesel & Co am Zimmerberg fanden in verschiedenen Pressehäusern Resonanz. 
Folgend einige Artikel und Verweise auf lesens- oder sehenswerte Publikationen: 

Vorläufiger Haupttext:

30. April 2021, Zürichsee-Zeitung "Landwirte und Wiesel helfen sich gegenseitig" (Abo)(https://www.zsz.ch/landwirte-und-wiesel-helfen-sich-gegenseitig-900393926751)

19. Mai 2021, Wädenswiler-/Richterswiler Anzeiger "Grosser Einsatz für kleine Raubtiere" (https://waedenswiler-anzeiger.ch/2021/05/19/grosser-einsatz-fuer-kleine-raubtiere)

12. Mai 2021, Kilchberger Gemeindeblatt "Mehr Lebensraum für Kleinraubtiere" [KIBG_s6_WiCoZ_21_05_12.pdf](https://github.com/wieselundco/website/files/6917895/KIBG_s6_WiCoZ_21_05_12.pdf)

Mai 2021, Ornis 3/21 "450 Strukturen für «Wiesel & Co» am Zimmerberg ZH" 
[Orn3_s2-WiCoZ_2.pdf](https://github.com/wieselundco/website/files/6917919/Orn3_s2-WiCoZ_2.pdf)

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/projekt-resultate/pressespiegel/

**Comment by ratnanil** [comment]
> Rubrik: News und Resultate (geht dies bei github auch?)

aktuell nicht, kann das aber noch versuchen wenn es wichtig ist

**Comment by wicoz** [comment]
> https://wieselundco.netlify.app/projekt-resultate/pressespiegel/
Danke fürs Erstellen. 

Wäre froh, wenn einige der kommenden Beiträge unter zwei Rubriken erscheinen. 

Kann man die Beiträge nicht einfach kopieren und an beiden Orten integrieren?
Magst Du dies mal versuchen (Pressespiegel unter News)?

**Comment by ratnanil** [comment]
ist der Artikel so fertig? wenn ja kann ich diese kopieren

**Comment by wicoz** [comment]
ich melde mich, sobald die betreffenden Artikel fertig sind

**Comment by wicoz** [comment]
habe nun den Beitrag ergänzt und Dateien angehängt (direkt in <Code>). 

Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben

Bitte folgendes Bild zudem als thumbnail:

![2018-08-20 13 22 44](https://user-images.githubusercontent.com/49158554/129121007-6ce0a617-2888-4f96-a1e6-0662ae97aca4.jpg)


und dieses im Beitrag: 
![schweizaktuell-stef](https://user-images.githubusercontent.com/49158554/129121054-4eb7d66e-e581-4012-ab17-8f7526bcbe47.JPG)

**Comment by ratnanil** [comment]
erledigt

**Comment by wicoz** [comment]
habe ein file ausgetauscht. Wenn dieses PDF drin ist, bitte eine Kopie unter Rubrik News erstellen mit demselben Datum.

**Comment by wicoz** [comment]
in Code geändertes Datum ist noch nicht online.

**Comment by ratnanil** [comment]
stimmt es jetzt?

**Comment by wicoz** [comment]
Dankeschön!
Habe im rmd noch Aufzählungszeichen ergänzt und die die Links so geschrieben, dass sie in neuem Fenster öffnen. 
bitte kompilieren und prüfen.

**Comment by ratnanil** [comment]
bitte kontrollieren

**Comment by wicoz** [comment]
perfekt
