### ISSUE TITLE
Neuer Beitrag: Schlussbericht

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#31]
@ratnanil
Bitte erstellen, damit ich diesen später ergänzen kann.
Bitte nur dann schon jetzt erstellen, wenn Du die Veröffentlichung auf Ende August einstellen kannst!

Rubrik: News und Resultate (geht dies bei github auch?)
Titel: Schlussbericht der Umsetzungsphase 2015 -2021
Datum: 30.8.21

Vorläufiger Starttext:
Das Projekt Wiesel & Co am Zimmerberg ist abgeschlossen. 
Die Inhalte dieser Website geben viele Impressionen zu den vergangenen Jahren. 
Die kürzlich publizierten Videosequenzen wagen sogar einen Ausblick in die Zukunft von Wiesel & Co am Zimmerberg
Der bebilderte Schlussbericht fasst die Resultate zusammen und wagt ebenfalls in kurzer Form einen Ausblick.
[PDF folgt] nebenstehendes Bild folgt

Vorläufiger Haupttext:

<<eigentlich braucht es ja keine subsite dazu, oder? >>

**Comment by ratnanil** [comment]
> Rubrik: News und Resultate (geht dies bei github auch?)

aktuell nicht, ich schau mal was ich machen kann

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/projekt-resultate/schlussbericht/

**Comment by wicoz** [comment]
Merci

Für mich: [PDF folgt] nebenstehendes Bild folgt

**Comment by wicoz** [comment]
Bitte folgendes Bild verwenden: 
![1b_Deckblatt_Schlussbericht-Phase2](https://user-images.githubusercontent.com/49158554/128784735-8934551e-efbe-45f8-b4c6-4248c16b873c.JPG)

**Comment by ratnanil** [comment]
Ich finde das bild zu lang als thumbnail.. kann man das kürzen?

![Screenshot from 2021-08-11 23-17-28](https://user-images.githubusercontent.com/12532091/129104723-747219e8-0290-40da-9672-4b66edcaedee.png)

**Comment by ratnanil** [comment]
ball ist wieder bei dir

**Comment by wicoz** [comment]
gern ersetzen

![Deckblatt_Schlussbericht-Phase2-SNIP](https://user-images.githubusercontent.com/49158554/129113794-021c7424-07d7-49f8-a36f-6380e39b8a83.jpg)

**Comment by ratnanil** [comment]
erledgit

**Comment by wicoz** [comment]
sehr gut. 
Melde mich im September wieder mit dem file upload und yumpu Link. 
Dieser Beitrag soll jetzt versteckt werden. - machst Du das?

Nach News kopieren erst im September, oder?

**Comment by ratnanil** [comment]
>  Dieser Beitrag soll jetzt versteckt werden. - machst Du das?

erledigt

> Nach News kopieren erst im September, oder?

ja

**Comment by wicoz** [comment]
Ich habe nun den Beitrag ergänzt: 

- Download Link
- yumpu embed code

ausserdem file hochgeladen.

Bitte kompilieren und prüfen. Wenns gut ausschaut und die Links funktionieren (werden), dann kannst Du gern gleich die Kopie nach News machen. 

Würds auch noch gern anschauen am Montag.

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/projekt-resultate/schlussbericht/
https://wieselundco.netlify.app/news/2021-09-01-schlussbericht/

**Comment by wicoz** [comment]
merci, Nils. 

Nun möglichst rasch verbergen. 

Habe in den beiden rmd's noch einen Schreibfehler korrigiert und 
"draft: true" nach preview: ... eingefügt. 

Bitte kompilieren und prüfen.

**Comment by ratnanil** [comment]
Bericht ist jetzt versteckt

**Comment by wicoz** [comment]
Ist noch immer öffentlich sichtbar unter 
https://wieselundco.ch/news
und 
https://wieselundco.ch/resultate

**Comment by ratnanil** [comment]
ist jetzt weder unter news noch resultate sichtbar
