### ISSUE TITLE
Beitrag Asthaufen: Fotos

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#32]
@ratnanil 
In https://wieselundco.github.io/website/projekt-massnahmen/114-hinweise-haufen/ werden zwei bisherige Bilder noch nicht angezeigt. 

Bitte ziemlich am Anfang (**Bild Hermelin in Asthaufen #32**) des Textes zudem dieses Foto einfügen.
![D90_20140605](https://user-images.githubusercontent.com/49158554/127888904-d6406100-e937-4c96-adc9-f5bd8afc576a.jpg)

**Comment by ratnanil** [comment]
erledigt https://wieselundco.github.io/website/projekt-massnahmen/114-hinweise-haufen/
