### ISSUE TITLE
Cookies Zustimmung

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#33]
@ratnanil  Brauchts so ein Ok von den NutzerInnen, das fast überall zu sehen ist?

**Comment by ratnanil** [comment]
ich sammle keine cookies, habe das also bisher nicht für nötig gehalten. wir können aber trotzdem danach fragen, wird jetzt neuerdings auch gemacht:

![grafik](https://user-images.githubusercontent.com/12532091/127994527-2b193b78-32a7-49b3-a601-0848fb3432fc.png)

**Comment by wicoz** [comment]
Nun ja  ; ) danke
Ich habe keine Ahnung, ob es das rechtlich braucht. 
sonst nervts ja eigentlich
