### ISSUE TITLE
@ratnanil Die INTUITIV SICHTBARE Verlinkung ist bisher nicht toll.

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/website#34]
@ratnanil Die INTUITIV SICHTBARE Verlinkung ist bisher nicht toll. 
Du hast rückgemeldet, dass ein Button o.ä. auf fortführende Inhalte nicht möglich sind.

Wie heben wir die Links in den Beiträgen SICHTBAR hervor? 
Farblich wie bisher (dunkelorange) finde ich eine gute Option. Mit eckigen Klammern find ich nicht toll.

_Originally posted by @wicoz in https://github.com/wieselundco/website/issues/13#issuecomment-891089041_

**Comment by ratnanil** [comment]
du sprichst von zwei verschiedenen Sachen glaube ich:

1. Verlinkung "weiterlesen" oder "mehr erfahren"
2. links auf andere Artikel oder externe websiten

stimmt das? 

Punkt 1 kann ich wie gesagt nicht ändern. Für Punkt 2 habe ich eine Kompromisslösung:

![grafik](https://user-images.githubusercontent.com/12532091/127998129-7498b66d-1f93-4f45-badd-5da0f10afdae.png)

**Comment by wicoz** [comment]
> du sprichst von zwei verschiedenen Sachen glaube ich:

ja, richtig verstanden

Mal schauen, wie die Kompromisslösung dann auf weissem Hintergrund und auf dem mobile aussehen wird. Ich denke, das passt, danke.
