### ISSUE TITLE
Bitte darauf achten, dass alle links auf externe Seiten in neuem Fenster öffnen.

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/website#35]

**Comment by ratnanil** [comment]
@wicoz : Um sicher zu stellen, dass URLs in einem neuen fenster geöffnet werden, muss man den URL folgendermassen im text einfügen:  `<a href="https://www.externeseite.com/" target="_blank">Text der angezeigt wird</a> `

also zum Beispiel: `<a href="http://wieselnetz.ch/de/" target="_blank">Die homepage von Wieselnetz</a> ` wird dann folgendermassen dargestellt: <a href="http://wieselnetz.ch/de/" target="_blank">Die homepage von Wieselnetz</a>

**Comment by ratnanil** [comment]
ich habe dies für bestehende Seiten korrigiert, für neue seiten müssen wir uns darauf achten

**Comment by wicoz** [comment]
Dankeschön. 
Ich werde beim Editieren der Beiträge schauen, ob ich das selber bewerkstelligen kann...

**Comment by wicoz** [comment]
versuche ich jetzt im Code einzufügen...


<a href="http://www.lotteriefonds.zh.ch/" target="_blank">Lotteriefonds Kanton Zürich</a>
<a href="http://www.fls-fsp.ch/" target="_blank">Fonds Landschaft Schweiz</a>
<a href="http://www.ernst-goehner-stiftung.ch/index.php/de" target="_blank">Ernst Goehner Stiftung</a>
<a href="http://temperatio.ch/" target="_blank">Temperatio Stiftung</a>

<a href="http://www.paul-schiller-stiftung.ch/" target="_blank">Paul Schiller Stiftung</a>
<a href="http://www.horgen.ch/" target="_blank">Gemeinde Horgen</a>
<a href="http://www.kilchberg.ch/" target="_blank">Gemeinde Kilchberg</a>
<a href="http://www.langnauamalbis.ch/" target="_blank">Gemeinde Langnau a.A.</a>
<a href="http://www.richterswil.ch/" target="_blank">Gemeinde Richterswil</a>
<a href="http://www.thalwil.ch/" target="_blank">Gemeinde Thalwil</a>
<a href="http://www.waedenswil.ch/" target="_blank">Gemeinde Wädenswil</a>
<a href="http://www.wls.ch/" target="_blank">WLS WildLife Solutions</a>
<a href="http://www.wieselnetz.ch/" target="_blank">Stiftung Wieselnetz</a>
<a href="https://aln.zh.ch/internet/baudirektion/aln/de/naturschutz.html" target="_blank">Fachstelle Naturschutz Kanton Zürich</a>
<a href="http://www.nv-schoenenberg.ch/" target="_blank">Fachstelle Naturschutz Kanton Zürich</a>
<a href="https://www.birdlife-zuerich.ch/home/" target="_blank">BirdLife Zürich</a>
<a href="http://www.lsfm.zhaw.ch/de/science/institute-zentren/iunr-integrativeoekologie/geoinformatik.html" target="_blank">Forschungsgruppen Geoinformatik und Wildtiermanagement der ZHAW Wädenswil</a>
<a href="http://www.cscf.ch/" target="_blank"> Centre Suisse de Cartographie de la Faune</a>
<a href="http://www.cashctrl.com/de/" target="_blank">Die Schweizer Online Buchhaltung
mit FREE Version.</a>
<a href="https://wildnispark.ch/" target="_blank"> Stiftung Wildnispark Zürich</a>

<a href="https://dokumentarfilme.ch" target="_blank">www.dokumentarfilme.ch</a>
<a href="http://www.syndrega.ch/" target="_blank">Syndrega GmbH</a>
<a href="http://www.illustrat.ch/" target="_blank">Illustrat, Atelier für Grafik und Illustration</a>

<a href="http://www.schluchtalhof.ch/" target="_blank">Werner und Karin Fankhauser, Schluchtalhof Wädenswil</a>
<a href="https://www.stallstreuli.ch/" target="_blank">Streuli Aktivstall, Horgenberg</a>
<a href="http://www.hintermannweber.ch/" target="_blank">Hintermann Weber</a>
