### ISSUE TITLE
Wie kann ich allg. die Reihenfolge von Beiträgen in einer Rubrik ändern?

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/website#36]
@ratnanil 
Wie kann ich allg. die Reihenfolge von Beiträgen in einer Rubrik ändern?
wie bisher übers Datum? 

Konkret: 
hier https://wieselundco.github.io/website/Welche-Massnahmen.html bitte diesen Beitrag zuunterst anordnen: 
https://wieselundco.github.io/website/projekt-massnahmen/59-welche-massnahmen-nuetzen-den-kleinra/

_Originally posted by @wicoz in https://github.com/wieselundco/website/issues/29#issuecomment-891126146_

**Comment by ratnanil** [comment]
>  wie bisher übers Datum?

ja, über das Datum. Machst du die Änderungen?

**Comment by wicoz** [comment]
ok, werd ich machen, wenn ich alles durchsehe - dasselbe mit den Absätzen, Textinhalten etc.
