### ISSUE TITLE
Kopfzeile (wenn zweizeilig) überschneidet leicht Inhalte

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#37]
in einem Bsp gesehen: 
https://wieselundco.github.io/website/TubeCam.html bei schmalem Fenster; 
Kopfzeile wird zweizeilig, Text oberhalb Titel "Tubecam" wird teilweise zugedeckt.

Wahrscheinlich ist die Lösung, dass der Titel zuerst kommt. 
Wo dies so ist, habe ich das Phänomen nicht entdeckt. 

Bitte gleich selber testen/korrigieren.

und für mich learning posten, danke.

**Comment by ratnanil** [comment]
Anscheinend kann man keinen Text in diese Übersichtsseiten packen. Habe diesen entfernt.

**Comment by wicoz** [comment]
Schade ist, dass auf dem mobile bzw. auf dem Desktop, wenn bei schmalem Fenster die Kopfzeile zweizeilig wird und dadurch den obersten Inhalt leicht überdeckt (Titel / Bilder): 
Gibt es da Lösungsansätze? Zb bei jeder Seite zuoberst eine Leerzeile einfügen?

**Comment by ratnanil** [comment]
>  Gibt es da Lösungsansätze? Zb bei jeder Seite zuoberst eine Leerzeile einfügen?

ne leider geht das nicht.. ich habe auch keine Idee wie man das lösen kann
