### ISSUE TITLE
Neuer Beitrag: Gesamtschau der Wirkungskontrolle 

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#38]
Bitte neuen Beitrag erstellen.
In Rubrik Resultate (später News)
Ich werde in der Folge nach Bedarf noch einige Änderungen vornehmen im .rmd

kursiv = Intro (description), Rest = Haupttext

__In den Jahren 2019 und 2020 hat die ZHAW Wädenswil in unserem Auftrag 50 der realisierten Asthaufen und 11 der realisierten Winterquartiere untersucht. Diese Erhebungen ergeben darüber Aufschluss, wie attraktiv die im Projekt umgesetzten Massnahmen für die Zielarten Hermelin, Mauswiesel und Iltis sind._

_Das Fazit: Sehr attraktiv!
Eine weitere Erkenntnis ist, dass ein gewisser Faktor besonders zur Attraktivität eines Asthaufens beiträgt...__

[Der Schlussbericht] (https://forschung.wieselundco.ch/erfolgskontrolle/) schafft eine Synthese von verschiedenen Erhebungen und Datensätzen. 

Die Resultate der erwähnten systematischen Wirkungskontrolle im Herbst 2019 und Frühling 2020 werden mit Bezug auf die erhobenen **Beobachtungsmeldungen** und die spontanen Wirkungskontrollen (2015 bis 2019 ) betrachtet und diskutiert.
![3b_Layout_Strukturen_edit](https://user-images.githubusercontent.com/49158554/128785922-51340572-3d9e-4408-89d7-6089e1de7f19.jpg)

**Die systematische Wirkungskontrolle** zeigt, dass im [Herbst 2019] (https://wieselundco.github.io/website/projekt-resultate/125-wk-etappe1) 49 % und im Frühling 2020 36% der 50 bei Asthaufen eingesetzten Spurentunnel einen Nachweis von Hermelin und/oder Iltis brachten.
Über beide Jahre kumuliert ergibt dies eine Nachweisrate von knapp 70 %. 
![3a_Layout_Nachweisquote_snip](https://user-images.githubusercontent.com/49158554/128785895-18027898-6090-4061-a70d-9e40dbaae121.jpg)

Diese Zahlen sind im nationalen wie internationalen Vergleich sehr hoch, was ebenso durch die **spontanen Wirkungskontrollen** bestätigt wird [(Bsp. von 2015/2016)] (https://wieselundco.github.io/website/projekt-resultate/80-massnahmen-sind-nachweislich-attrakti/). 

Die Grössenverhältnisse der Nachweise zwischen unseren drei Zielarten werden zudem durch den Datensatz der gesammelten **Beobachtungsmeldungen** bestätigt.

Interessant ist auch die folgende **Erkenntnis für die Praxis**: 
Sind die Holzstrukturen aus grobem Material aufgebaut, steigt ihre Attraktivität für Hermelin und Iltis hoch signifikant. 
Nebst der guten Zugänglichkeit dürfte ein weiterer Grund die vorteilhafte Bekletterbarkeit und damit die Ermöglichung des räumlichen Überblicks zur Feindvermeidung sein. Idealerweise wird ein Asthaufen von Beginn weg aus grobem, massivem Material wie Wurzelstöcken, Stamm- und Stangenholz aufgebaut - bestenfalls aus beständigen Holzarten. Denn die realisierten Asthaufen sollen auch möglichst lange bestehen.

![1l_heusser](https://user-images.githubusercontent.com/49158554/128786177-a51b02ca-783a-48e5-8778-247ae4291f02.JPG)

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/projekt-resultate/2021-08-12-gesamtschau-der-wirkungskontrolle/

**Comment by wicoz** [comment]
Bitte 
![spur-wq](https://user-images.githubusercontent.com/49158554/129116401-4c31ce31-2a54-4d6c-a4e7-0c589f863533.jpg)
als thumbnail einfügen und Beitrag nach "Wirkungskontrolle" verschieben

**Comment by ratnanil** [comment]
ist jetzt hier: https://wieselundco.netlify.app/wirkungskontrolle/2021-08-12-gesamtschau-der-wirkungskontrolle/

auch hier finde ich die höhe des thumbnails nicht ideal

![image](https://user-images.githubusercontent.com/12532091/129353066-0ecc508f-559a-4702-8dd7-d4fba14c3b10.png)

**Comment by wicoz** [comment]
Lass ich mal so, wenn es Dich nicht seehr stört. ; )
