### ISSUE TITLE
Neuer Beitrag: Letzte Feldscheunen aufgewertet - wie weiter?

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#39]
Bitte neuen Beitrag erstellen.
In Rubrik Resultate (später News)
Ich werde in der Folge nach Bedarf noch einige Änderungen vornehmen im .rmd

kursiv = Intro (description), Rest = Haupttext

Am Schluss Galerie einfügen! Gallerie: https://flic.kr/s/aHsmWnRi66

_In der Schlussphase des Projektes konnten zwei weitere Streu- bzw. Torfhütten in Stand gestellt und mit Strukturen für Wiesel & Co ausgestattet werden.
Sie befinden sich am rund ums Chrutzelenmoos.
Erfahren Sie mehr und machen sich ein Bild von den Sanierungen._ 

[Diese Hintergründe und Rahmenbedingungen] (https://wieselundco.github.io/website/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/) begleiteten uns bei der Instandstellung und Aufwertung von Feldscheunen. 
In den vergangenen Monaten zeigten die Besitzer erneut viel Eigenleistungen, so dass man von einem langfristigen Erhalt dieser für Natur & Landschaft wertvollen Objekte ausgehen kann.
![43_2021-05-23_Forenmoos2-denoise-denoise_MJaeger_1500px](https://user-images.githubusercontent.com/49158554/128791183-69f69152-4a43-4ae4-aa13-73737174a43e.jpg)

Zum Projektabschluss sind 8 von 10 zum Ziel gesetzten Feldscheunensanierungen erfolgt, wobei uns verhältnismässig viel weniger finanzielle Mittel zur Verfügung standen als erwartet. 
Mindestens zwei weitere Feldscheunenbesitzer stellten uns mündlich in Aussicht, in Zukunft ohne Unterstützung von WiCoZ ihre Streuhütten in Schuss zu halten. 

In allen Fällen wurden für Wiesel & Co Unterschlüpfe eingerichtet und z.T. auch für Turmfalken & Schleiereulen Nisthilfen montiert. 
Beachten Sie dazu bitte die älteren Beiträge in der Rubrik 'Resultate'.
![39_FS-Seeli_1000px](https://user-images.githubusercontent.com/49158554/128788707-3dd05719-97b0-4dc3-a992-4b04f0a0c445.jpg)

Wie weiter? 
Für künftige Bestrebungen zum Erhalt dieser typischen Landschaftselemente im Bezirk Horgen hat WiCoZ im Projektverlauf ein Inventar erstellt. Darin sind 168 Objekte enthalten, wobei den meisten kein gleichzeitig kulturlandschaftlich und ökologisch hochstehendes Potential beigemessen wurde. Jene Objekte, die aus obigen Gründen sehr erhaltenswert sind, könnten hingegen in Zukunft angegangen werden.

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/projekt-resultate/2021-08-12-letzte-feldscheunen-aufgewertet-wie-weiter/

**Comment by wicoz** [comment]
![23_22_2021-05-28 16 55 55_1500px](https://user-images.githubusercontent.com/49158554/129117922-8c8120d3-644f-4cd7-8be2-d55280667437.jpg)
Bitte als thumbnail einfügen

**Comment by ratnanil** [comment]
ich finde diese hochformatigen bilder sehen einfach nicht gut aus. zudem: besser auf eine kleinere grösse skalieren, dann lädt das bild schneller. Du kannst das bild auch direkt hier hochladen: /_projekt-resultate/94-feldscheunen-sanierung-2016-7/

**Comment by wicoz** [comment]
neues thumbnail haben wir live eingefügt; 
ist aber noch nicht auf der Website. 

dann bitte noch die verbliebenen Dateibezeichnungen löschen, die unter den Bildern erscheinen. 

Weblink zuoberst im Haupttext funktioniert komischerweise nicht, obwohl Adresste stimmt.-> "Diese Hintergründe und Rahmenbedingungen"

ich korrigier im code grad noch einen Schreibfehler.

**Comment by ratnanil** [comment]
> neues thumbnail haben wir live eingefügt;

ist jetzt aktualisiert

> dann bitte noch die verbliebenen Dateibezeichnungen löschen, die unter den Bildern erscheinen.

erledigt

> Weblink zuoberst im Haupttext funktioniert komischerweise nicht, obwohl Adresste stimmt.-> "Diese Hintergründe und Rahmenbedingungen"

auf der website funktioniert der link

**Comment by wicoz** [comment]
Bei mir immernoch untenstehende Meldung. 

habe nun im rmd den ganzen Pfad eingefügt. Bitte kompilieren und prüfen. 

![image](https://user-images.githubusercontent.com/49158554/130317219-bf8d693f-509b-4e3f-8eaf-4587cb124790.png)

**Comment by ratnanil** [comment]
> habe nun im rmd den ganzen Pfad eingefügt. Bitte kompilieren und prüfen.

bitte mach das nicht, siehe https://github.com/wieselundco/website/issues/6#issuecomment-901506117


> Bei mir immernoch untenstehende Meldung.

Wie passiert das? Kannst du etwas expliziter sein? Wenn ich auf https://wieselundco.netlify.app/projekt-resultate/2021-08-12-letzte-feldscheunen-aufgewertet-wie-weiter/ gehe und dort auf den link klicke (screenshot unten) dann komme ich auf https://wieselundco.netlify.app/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/

![image](https://user-images.githubusercontent.com/12532091/130586300-6978513b-504b-4ad1-95ba-a3d057cb283f.png)

**Comment by wicoz** [comment]
ok, mach ich halte mich an die relativen Pfade! 
mittlerweile funktioniert bei mir der Link auch... 

noch etwas kleines: 
unter https://wieselundco.netlify.app/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/ erscheint rechts im preview so ein EIN-AUS Zeichen, dessen Grund ich im rmd nicht sehe:
![image](https://user-images.githubusercontent.com/49158554/130616184-4b1530a2-90d8-474b-8e98-d6e01cc2e5fb.png)

Übrigens hier #61 noch nicht erfolgt

**Comment by wicoz** [comment]
Nachtrag: 

habe das Preview im rmd leicht angepasst. 
Bitte zuerst kompilieren und schauen ob das EIN-AUS weg ist.

**Comment by ratnanil** [comment]
bitte kontrollieren

**Comment by wicoz** [comment]
perfekt
