### ISSUE TITLE
Neuer Beitrag: Effekt der faunagerechten Sanierung des Durchlasses Zugerstrasse

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#41]

**Comment by wicoz** [comment]
Bitte neuen Beitrag erstellen.
In Rubrik Resultate (später News)
Ich werde in der Folge nach Bedarf noch einige Änderungen vornehmen im .rmd

kursiv = Intro (description), Rest = Haupttext

preview Bild: 
![WKKamera1-1stePosition-snip](https://user-images.githubusercontent.com/49158554/128798178-54c809da-c6b3-463c-835c-cf032d65b68f.jpg)


_Der Gewässerdurchlass des Aabachs unter der Zugerstrasse befindet sich auf Stadtgebiet Wädenswil. Da er auf der gesamten Breite Wasser führt und keine naturnahen Elemente aufweist , überquerten die meisten Wildtiere an dieser Stelle die stark befahrene Strasse. 
Die faunagerechte Sanierung durch das Tiefbauamt des Kantons Zürich setzte sich zum Ziel, dass Kleintiere künftig den Durchlass passieren.
Welche Massnahmen werden getroffen und wie ist ihre Wirkung?_


![Portal-oben-saniert-total](https://user-images.githubusercontent.com/49158554/128798305-7542f956-d07c-49f1-84cc-472af57f7d0c.jpg)
Im Jahr 2019 wurde der Durchlass [entsprechend unseren Absichten] (LINK BEITRAG  Gewässerdurchlässe faunagerecht gestalten) saniert. Zugunsten der Durchlässigkeit für Kleintiere (Fuchs und kleiner) wurden beidseitig Betonbankette mit Laufflächen installiert. Zudem bieten integrierte Unterschlüpfe insbesondere Kleinsäugern und Wieseln die Möglichkeit auf dem Weg Deckung aufzusuchen. 

![verstopfteUnterschluepfe (1)](https://user-images.githubusercontent.com/49158554/128798263-2b631e29-7c78-45df-8660-56c4fd0cd1d5.JPG)


Unsere aufwändige Wirkungskontrolle mit Fotofallen zeigt nach 10 monatiger Aufnahme des Ausgangszustands und eben so langer Erhebung des Sollzustandes bisher geringe Wirkung. 
Welche Tierarten die Laufflächen bereits benutzen und welche nach wie vor nur an den Portalen nachgewiesen werden, zeigt der folgende Bericht. Die Diskussion der Resultate führt zu Massnahmenempfehlungen, die die Frequentierung der Laufflächen in Zukunft steigern sollen. 

[DOWNLOAD BERICHT ](https://github.com/wieselundco/website/files/6967598/WK_WiCoZ_Durchlass-Zugerstr.pdf)


Bitte auch mit  YUMPU LINK LESEANSICHT EINBETTEN 
<style>.embed-container { position: relative; padding-bottom:56.25%; height:0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%;}</style><div class='embed-container' data-page-width='453' data-page-height='640' id='ypembedcontainer' ><iframe   src="https://www.yumpu.com/de/embed/view/ocJewdRnOs6SjEM3" frameborder="0" allowfullscreen="true"  allowtransparency="true"></iframe><br><a href="https://www.yumpu.com/de/document/view/65808538/wirkungskontrolle-durchlass-zugerstrasse" title="Wirkungskontrolle Durchlass Zugerstrasse" target="_blank">Wirkungskontrolle Durchlass Zugerstrasse</a></div><script src='https://players.yumpu.com/modules/embed/yp_r_iframe.js' ></script>

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/news/2021-08-11-effekt-der-faunagerechten-sanierung-des-durchlasses-zugerstrasse/

**Comment by wicoz** [comment]
Habe gestern im <Code> im Haupttext noch einen Link eingefügt, sonst super. 

Sobald dies gemacht ist, noch nach Rubrirk "Wirkungskontrolle" kopieren.

**Comment by ratnanil** [comment]
dieser link kommt noch hinzu: 
https://wieselundco.netlify.app/wirkungskontrolle/2021-08-11-effekt-der-faunagerechten-sanierung-des-durchlasses-zugerstrasse/

**Comment by wicoz** [comment]
hab unter #40 den Querlink auf diesen Beitrag aktualisiert. Sollte jetzt funktionieren.
