### ISSUE TITLE
Neuer Beitrag: Sehenswerte Projekt-Videos mit Interviews u.v.m. 

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#42]
Bitte neuen Beitrag erstellen.
In Rubrik News (später ev. Resultate)
Ich werde in der Folge nach Bedarf noch einige Änderungen vornehmen im .rmd

wird versteckt, wenn page live geht.

kursiv = Intro (description), Rest = Haupttext

preview Bild:

**Comment by wicoz** [comment]
Bitte neuen Beitrag erstellen.
In Rubrik News (später ev. Resultate)
Ich werde in der Folge nach Bedarf noch einige Änderungen vornehmen im .rmd

wird versteckt, wenn page live geht.

kursiv = Intro (description), Rest = Haupttext

preview Bild: 
![Titelbild Begegnungen](https://user-images.githubusercontent.com/49158554/128898050-0d8849c5-39a5-42e7-a9cc-9ad41bf224ca.JPG)



_Reservieren Sie sich einen kleinen Heimkinoabend mit Wiesel & Co!_

_Zum Projektabschluss war keine Präsenzveranstaltung mit Podiumsdiskussion möglich. 
Rückblickend ein Glücksfall? 
Wiesel & Co am Zimmerberg hat 15 Projektbeteiligte interviewt und viele tolle Kurzvideos und Bilder aus dem Archiv zu sehenswerten Kurzfilmen zusammengestellt._

Statt der Präsenzveranstaltung sind in der Schlussphase zwei semiprofessionelle Videos entstanden, die mit unterschiedlichen Stimmungen aufwarten. 

Wir würden uns sehr freuen, wenn Sie sich Zeit nehmen, um die Videos anzuschauen und mit Freunden zu teilen. Sie dauern jeweils ca. 1/4 bzw. 1/2 Stunde.

[**"Begegnungen mit Wiesel & Co"**](youtube Link folgt wohl erst im September) wartet u.a. mit einem einzigartigen Nachweis der Hermelin-Jugend im Garten eines berühmten Wädenswiler Kinderliedermacher auf. Wir stellen den Interviewpartnern die witzige Frage: "Was ist eigentlich ein Wieseltanz?" 


[**"Was bringt die Zukunft für Wiesel & Co am Zimmerberg?»**](youtube Link folgt wohl erst im September) geht mehr in die Tiefe und erörtert, wie verschiedene Aspekte des Projektes wahrgenommen werden. Beispielsweise: 
- die erzielten Resultate und Effekte
- die Form der Zusammenarbeit
- der Mehrwert der Regionalität
- bearbeitete Lösungsansätze
- und der Blick in die Zukunft ...

... denn ist Ihnen schon bekannt, dass derzeit die [Trägerschaft des Naturnetzes Zimmerberg aufgebaut wird?] (LINK auf Beitrag Das Ende vom Anfang - Naturnetz Zimmerberg wird aufgebaut!) 


HIER UNTEN DIE BEIDEN YOUTUBE FILME (AUCH NOCH) EINBETTEN.

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/news/2021-08-11-sehenswerte-projekt-videos-mit-interviews-uvm/

todo:
- [ ] HIER UNTEN DIE BEIDEN YOUTUBE FILME (AUCH NOCH) EINBETTEN.
- [ ] ["Was bringt die Zukunft für Wiesel & Co am Zimmerberg?»](youtube Link folgt wohl erst im September)
- [ ] ["Begegnungen mit Wiesel & Co"](youtube Link folgt wohl erst im September)

**Comment by wicoz** [comment]
diesen Beitrag bitte jetzt verstecken.

Ich werde mich dann mit dem Einbetten/Verlinken nach Mitte September melden und wir kontrollieren dann die Datumreihenfolge nochmals.

**Comment by ratnanil** [comment]
bitte kontrollieren
