### ISSUE TITLE
Neuer Beitrag: Das Ende vom Anfang - Naturnetz Zimmerberg wird aufgebaut!

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#43]
Bitte neuen Beitrag erstellen.
In Rubrik News
Ich werde in der Folge nach Bedarf noch einige Änderungen vornehmen im .rmd

wird versteckt, wenn page live geht.

kursiv = Intro (description), Rest = Haupttext

preview Bild:
![NV-Schoenenberg-Wanderung-snip-hochf(7)](https://user-images.githubusercontent.com/49158554/128901062-496cf831-ec15-415c-a26e-8dc8da2278b3.jpg)

_Nach einem zusätzlichen Jahr und total 7 1/2 Jahren Projektdauer geht Wiesel & Co am Zimmerberg jetzt definitiv zu Ende. 
Es war uns eine Freude, in verschiedenster Hinsicht. Danke & Gerngeschehen._
 
_Und es geht weiter in anderer Form weiter, entschiedener und engagierter wie nie zuvor._

Um die Errungenschaften, das Netzwerk und das Knowhow in Zukunft zu nutzen, bleibt diese Website mit Ihren zahlreichen Dokumenten und Praxishilfen bis auf Weiteres bestehen. 

[**Je Trägerschaftsverein gibt es weiterhin eine Ansprechperson**]
 (https://wieselundco.github.io/website/ueber-uns/27-die-traegerschaft-wir-stellen-uns-vor/), die künftig auf Ihre Fragen und Anliegen zu Wiesel & Co eingeht bzw. für das Anliegen nach Bedarf an die passende Person weiterverweist.

[Richten Sie ihre **Beobachtungsmeldungen** bitte in Zukunft ans CSCF](https://wieselundco.github.io/website/Beobachtung-Melden.html) - dort sind auch die bisherigen gesammelten Daten gut aufgehoben und werden zugunsten unserer Wildtiere und ihrer Lebensräume genutzt.

Eines unserer beiden projekteigenen Videos, [**"Was bringt die Zukunft für Wiesel & Co am Zimmerberg?»**](youtube Link folgt wohl erst im September) erörtert aus Sicht der Projektbeteiligten, welchen Herausforderungen zukünftig mit welchen Lösungsansätzen begegnet werden kann und welche Visionen schon vorhanden sind.

![Titelbild Zukunft](https://user-images.githubusercontent.com/49158554/128899128-2b4de64d-f277-45c6-beba-5a3da3a2e969.JPG)

Inzwischen wurde das **Naturnetz Zimmerberg** initiiert und befindet sich in der zweiten Phase, dem Aufbau einer breit abgestützten Trägerschaft. 
Damit gewichtige Interessengruppen mit Bezug zu Natur & Landschaft eine geeignete Form der Zusammenarbeit, gemeinsame Ziele und erste Projektideen entwickeln können, hat die Zürcher Planungsgruppe Zimmerberg finanzielle Mittel für den Trägerschaftsaufbau gesprochen. 
![IMG_3496](https://user-images.githubusercontent.com/49158554/128898851-f90d1665-ff45-4081-9384-347fa7bc3452.jpg)

Dieses Bekenntnis der Standortgemeinden ist ein wichtiges Signal für weitere Körperschaften u.a. aus Landwirtschaft, Forst, Jagd & Fischerei, Naturschutz, Stanortförderung etc. 
Die [Zürichsee-Zeitung berichtete am 2. August 2021](https://www.zsz.ch/neues-netzwerk-soll-natur-am-linken-seeufer-foerdern-822039542417) von der ersten Infoveranstaltung und den Hintergründen und Aktualitäten.

Herzliche Dank fürs bisherige Engagement und in Zuekunft vill Freud und Erfolg bim Isatz für d Natur & Landschaft am Zimmerberg!

HIER UNTEN DIE BEIDEN YOUTUBE FILME EINBETTEN (wie im Video-Beitrag).

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/news/2021-08-11-das-ende-vom-anfang-naturnetz-zimmerberg-wird-aufgebaut/

> HIER UNTEN DIE BEIDEN YOUTUBE FILME EINBETTEN (wie im Video-Beitrag).

das machst du noch oder?

**Comment by wicoz** [comment]
`HIER UNTEN DIE BEIDEN YOUTUBE FILME EINBETTEN (wie im Video-Beitrag).

das machst du noch oder?

ja, aber erst im September, mit dem letzten Newsletter. 

ich füge jetzt die Bemerkung jetzt wieder ein. 

Sobald wir die Website aufschalten, wird dieser Beitrag dann versteckt. Bitte bis dann noch mit verstecken zuwarten, damit ich die Übersicht behalte.

**Comment by wicoz** [comment]
diesen Beitrag bitte jetzt verstecken.

Ich werde mich dann mit dem Einbetten/Verlinken nach Mitte September melden und wir kontrollieren dann die Datumreihenfolge nochmals.

**Comment by ratnanil** [comment]
bitte überprüfen

**Comment by wicoz** [comment]
super!
