### ISSUE TITLE
Rubriken ordnen

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#44]
Im Wissen, dass ich dann wohl noch die internen Links noch updaten muss, möchte ich Dich um folgende Ordnung bitten. 
Ich beziehe mich hier nur auf Haupt- und Unterrubriken - nicht auf Beiträge!
Welche Beiträge wohin zu verschieben sind bzw. gelöscht werden sollen, werde/habe ich in den einzelnen Beiträgen vermerken/rt. (Mit der Funktion Commit Changes -> Add an optional extended description.)

DAS PROJEKT 
Ausgangslage und Ziele
Resultate
NEU ERSTELLEN: Wirkungskontrolle (bestehende Beiträge hierhin verschieben)
Bonus System

WISSENSCHAFT 
gut so

FÖRDERUNG 
Welche Massnahmen? 
TITEL ÄNDERN: Praktischer Naturschutz  STATT Anpacken
NEU HIER: Wühlmäuse im Griff?
NEU ERSTELLEN: Infoveranstaltungen (bestehende Beiträge hierhin verschieben)

FASZINATION KLEINRAUBTIERE
Unsere Zielarten
Mensch und Wiesel
Beobachtungen STATT Beobachtung melden

ÜBER UNS
gut so 

NEWS
gut so

**Comment by ratnanil** [comment]
welche beträge meinst du genau? am liebsten github pfade angeben

- [ ]  Wirkungskontrolle (bestehende Beiträge hierhin verschieben)
- [ ]  Infoveranstaltungen (bestehende Beiträge hierhin verschieben)

**Comment by wicoz** [comment]
teile ich Dir so mit, ok?
`Welche Beiträge wohin zu verschieben sind bzw. gelöscht werden sollen, werde/habe ich in den einzelnen Beiträgen vermerken/rt. (Mit der Funktion Commit Changes -> Add an optional extended description.)`

**Comment by ratnanil** [comment]
aus #50

> Als ich gestern in diversen Beiträgen (v.a. aus News) in ` kleinere Anpassungen gemacht hatte, beschrieb ich vor dem Absenden im description Feld teilweise die gewünschte Verschiebung nach Unter-Rubrik "xy".`
> ` Ich glaube, ich hatte da versehentlich mehrmals geschrieben, aber die Rubrik "Infoveranstaltungen" gemeint. -> Rubrik "Infoveranstaltungen" ist der richtige Name und nicht "Öffentlichkeitsarbeit"`

**Comment by ratnanil** [comment]
- [ ] **2021-08-12 Update 7-partner.Rmd**: vgl. #35 (ca22dd6)
- [ ] **2021-08-12 Update 7-partner.Rmd**:  (e3cf336)
- [ ] **2021-08-12 Add files via upload**:  (4abefa9)
- [ ] **2021-08-12 Update pressespiegel.Rmd**: File "Februar 2015, Zürichsee-Zeitung "Wie die Wiesel im Bezirk überleben sollen"" ausgetauscht, vgl. upload file (abaa413)
- [ ] **2021-08-12 Update 126-mammaliabox.Rmd**: auf der Website ist dieser code sichtbar ganz zuunterst: 
Bitte ersetzen gemäss #46  {gallery}fotos/MammaliaBox{/gallery} (442357d)
- [ ] **2021-08-12 Add files via upload**:  (4e16323)
- [ ] **2021-08-12 Update 39-zur-interaktiven-karte.Rmd**: bitte PDF verlinken, das ich raufgeladen habe (06d5877)
- [ ] **2021-08-12 Add files via upload**: bitte diese files an entsprechender Stelle verlinken (787c14d)
- [ ] **2021-08-12 Update 117-info-dossier-und-workshop-2.Rmd**: bitte heraufgeladenen PDF's einfügen (2844761)
- [ ] **2021-08-12 Update 104-bekaempfung-mit-verstand.Rmd**:  (54321cf)
- [ ] **2021-08-12 Update 103-ein-schaedling-mitnichten.Rmd**:  (e13cea5)
- [ ] **2021-08-12 Update 8-gemischtes-doppel.Rmd**: Wasserrinne Bild raufgeladen - bitte einfügen, (69196ce)
- [ ] **2021-08-12 Add files via upload**: Bitte Bild Wasserrinne noch an entsprechender Stelle einfügen. (dbc739b)
- [ ] **2021-08-12 Update 12-who-is-who.Rmd**:  (199eca6)
- [ ] **2021-08-12 Update 37-fragen-rund-um-die-wiesel-2.Rmd**:  (2747e9d)
- [ ] **2021-08-12 Update 36-fragen-rund-um-die-wiesel.Rmd**:  (dcda1e5)
- [ ] **2021-08-12 Update 41-spannende-kurzfilme.Rmd**:  (ac51cb3)
- [ ] **2021-08-12 Update effekt-der-faunagerechten-sanierung-des-durchlasses-zugerstrasse.Rmd**:  (54c6c19)
- [ ] **2021-08-12 Update 2021-04-19-138-atlas-der-saeugetiere.Rmd**:  (b10d29c)
- [ ] **2021-08-12 Update 2021-03-14-128-wicoz-bilanz.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (ea79eca)
- [ ] **2021-08-12 Update 2020-01-26-123-aktionstage-feb-20.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (7bb4e44)
- [ ] **2021-08-12 Update 2019-12-26-127-projektverlaengerung.Rmd**:  (e1b504e)
- [ ] **2021-08-12 Update 2019-11-29-122-aktionstage-dez-19.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (ded4c59)
- [ ] **2021-08-12 Update 2019-10-16-119-exkursion-klein-ganz-gross.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (45cfaa4)
- [ ] **2021-08-12 Update 2019-10-16-116-workshop-wuehlmaeuse-im-gr.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (66d6dd4)
- [ ] **2021-08-12 Update 2019-03-08-113-pflanzung-wolfbuehl-maerz2.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (24d9865)
- [ ] **2021-08-12 Update 2017-11-07-102-exkursion-12-nov-resultate.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (fe193c9)
- [ ] **2021-08-12 Update 2017-04-03-96-sonderausstellung-wildnispa.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (be145b4)
- [ ] **2021-08-12 Update 2017-04-03-95-aktionstage-april-2017.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (5ffb753)
- [ ] **2021-08-12 Add files via upload**: bitte an entsprechendem Ort einfügen (321b6c6)
- [ ] **2021-08-12 Update 2017-02-15-111-strukturenbau-14-april.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben

ergänztes PDF lade ich auch noch via "upload file" hoch (6a5fe8a)
- [ ] **2021-08-12 Update 2017-02-15-81-aktionstage-februar-2017.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (b03fe4b)
- [ ] **2021-08-12 Update 2017-01-30-79-hecken-und-waldrandpflegeku.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (01d88bf)
- [ ] **2021-08-12 Update 2017-01-26-29-erste-moeglichkeiten-zum-mi.Rmd**:  (4a91e4b)
- [ ] **2021-08-12 Update 2017-01-26-29-erste-moeglichkeiten-zum-mi.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (b639909)
- [ ] **2021-08-12 Update 2016-04-08-72-teamaktion-mit-wiesel-co-am.Rmd**: Hier bitte löschen, aber nicht derselbe Beitrag unter"Praktischer Naturschutz" (ex-Anpacken) (8f86a57)
- [ ] **2021-08-12 Update 2016-03-08-71-aststrukturen-bauen-sa-12-m.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (1242e5b)
- [ ] **2021-08-12 Update 2016-03-08-71-aststrukturen-bauen-sa-12-m.Rmd**:  (f3459ab)
- [ ] **2021-08-12 Update 2016-03-07-74-aktionstage-april-2016.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (db02705)
- [ ] **2021-08-12 Update 2016-02-26-70-mit-ferienpass-kleinstruktu.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (c66a80c)
- [ ] **2021-08-12 Update 2016-01-28-68-einladung-zur-infoveranstal.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (4e5023c)
- [ ] **2021-08-12 Update 2014-01-29-16-exkursion-kleinraubtiere-ke.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (8b4b9c8)
- [ ] **2021-08-12 Update 2014-01-29-15-paul-marchesi-ist-verstorbe.Rmd**:  (2462870)
- [ ] **2021-08-12 Update 2014-01-29-18-unser-faltblatt.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (5f80785)
- [ ] **2021-08-12 Update 7-partner.Rmd**:  (5d0ae0f)
- [ ] **2021-08-12 Update 23-organigramm.Rmd**:  (e19f6eb)
- [ ] **2021-08-12 Update 24-kontakt.Rmd**: ist das für Dich so ok mit deiner Kontaktangabe? (3c7ef35)
- [ ] **2021-08-12 Update 27-die-traegerschaft-wir-stellen-uns-vor.Rmd**:  (7ac1e23)
- [ ] **2021-08-12 Add files via upload**: Bitte als thumnail und im Beitrag einfügen (f239f17)
- [ ] **2021-08-12 Update 39-zur-interaktiven-karte.Rmd**:  (1c69802)
- [ ] **2021-08-12 Add files via upload**: bitte als thumbnail und im Beitrag einfügen (c4b8b59)
- [ ] **2021-08-12 Update 39-zur-interaktiven-karte.Rmd**: die eigentliche Karte ist zwar noch aktiv und muss es vorübergehend noch bleiben, aber der Text ist hier bereits angepasst. 

Bitte noch Bild einfügen (via upload file gesendet) als thumbnail und im Hauptbeitrag. (c1f0699)
- [ ] **2021-08-12 Update 33-eine-beobachtung-melden-3.Rmd**:  (aaeaae7)
- [ ] **2021-08-12 Delete 32-eine-beobachtung-melden-2.Rmd**:  (ee9264c)
- [ ] **2021-08-12 Update 28-warum-und-wozu-hilft-meine-sichtungs-.Rmd**:  (836c00e)
- [ ] **2021-08-12 Delete 40-zum-kontaktformular.Rmd**:  (e2f3852)
- [ ] **2021-08-12 Delete 22-kontaktformular.Rmd**:  (509b5a9)
- [ ] **2021-08-12 Update 108-wieselwerk-mit-schulklassen.Rmd**:  (29b679b)
- [ ] **2021-08-12 Update 75-teamtraining-mit-wiesel-co-am-zimmerb.Rmd**:  (2d42291)
- [ ] **2021-08-12 Delete 21-sponsoring.Rmd**:  (82a5bee)
- [ ] **2021-08-12 Delete 20-anpacken.Rmd**:  (7247b53)
- [ ] **2021-08-12 Update gewsserdurchlsse-faunagerecht-gestalten.Rmd**:  (9aaf4ee)
- [ ] **2021-08-12 Update 132-gross-struktur.Rmd**:  (6ea41fb)
- [ ] **2021-08-12 Update 114-hinweise-haufen.Rmd**:  (321b5de)
- [ ] **2021-08-12 Update 135-winterquartier.Rmd**:  (cdbda35)
- [ ] **2021-08-12 Update 107-hecken-und-waldrandaufwertungen.Rmd**:  (28cfdec)
- [ ] **2021-08-12 Update 62-wir-unterstuetzen-die-instanstellung-.Rmd**:  (8d3ba44)
- [ ] **2021-08-12 Update 62-wir-unterstuetzen-die-instanstellung-.Rmd**:  (b5ce2b1)
- [ ] **2021-08-12 Update 107-hecken-und-waldrandaufwertungen.Rmd**:  (b55bfef)
- [ ] **2021-08-12 Update 135-winterquartier.Rmd**:  (66bd526)
- [ ] **2021-08-12 Update gewsserdurchlsse-faunagerecht-gestalten.Rmd**:  (2aaaf98)
- [ ] **2021-08-12 Update 132-gross-struktur.Rmd**:  (2bdbf8d)
- [ ] **2021-08-12 Update 59-welche-massnahmen-nuetzen-den-kleinra.Rmd**:  (4ce12f1)
- [ ] **2021-08-12 Update 114-hinweise-haufen.Rmd**:  (ec34f12)
- [ ] **2021-08-12 Update 131-nistkammer-monitoring.Rmd**: funktioniert das unterste Bild nun? (0b767de)
- [ ] **2021-08-12 Update 126-mammaliabox.Rmd**:  (b89d599)
- [ ] **2021-08-12 Update 85-stand-der-entwicklung.Rmd**: funktioniert Bild jetzt? (da6f8f6)
- [ ] **2021-08-12 Add files via upload**: handelt sich um Doppel, der in den code geladenen Dokumente - bitte an entsprechenden Stellen einfügen. (92c3560)
- [ ] **2021-08-12 Update pressespiegel.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (dfb9f06)
- [ ] **2021-08-12 Update 2-motivation.Rmd**:  (6dd62e1)
- [ ] **2021-08-12 Update gesamtschau-der-wirkungskontrolle.Rmd**: Bitte nach neuer Unter-Rubrik "Wirkungskontrolle" verschieben (51e2b6a)
- [ ] **2021-08-12 Update 134-acht-streuhuetten-saniert.Rmd**:  (78e9c29)
- [ ] **2021-08-12 Update 133-erste-mast-strukturen.Rmd**:  (f0d9af2)
- [ ] **2021-08-12 Update 129-zwischenbericht-2019.Rmd**:  (df5c137)
- [ ] **2021-08-12 Update 125-wk-etappe1.Rmd**:  (121ab0b)
- [ ] **2021-08-12 Update 124-souvenir-dez-2019.Rmd**:  (5633cbe)
- [ ] **2021-08-12 Update 121-zwischenbericht-2018.Rmd**:  (650beed)
- [ ] **2021-08-12 Update 120-drei-streuhuetten-sind-saniert.Rmd**:  (85ef1f6)
- [ ] **2021-08-12 Update 118-ueberarbeitete-karten-fuer-massnahme.Rmd**:  (14eec50)
- [ ] **2021-08-12 Update 112-beispiel-mosli.Rmd**:  (b83e1e7)
- [ ] **2021-08-12 Update 110-feldscheunen-sanierung-2018-03.Rmd**:  (8f1d1c8)
- [ ] **2021-08-12 Update 109-zwischenbericht-2017-von-phase-2.Rmd**:  (31b75ba)
- [ ] **2021-08-12 Update 101-feldscheunen-sanierung-2017-10.Rmd**:  (0b561c3)
- [ ] **2021-08-12 Update 100-massnahmenstande-ende-2016.Rmd**:  (f43dc41)
- [ ] **2021-08-12 Update sehenswerte-projekt-videos-mit-interviews-uvm.Rmd**:  (72bbc37)
- [ ] **2021-08-12 Update schlussbericht.Rmd**:  (523021b)
- [ ] **2021-08-12 Update 133-erste-mast-strukturen.Rmd**:  (d349a70)
- [ ] **2021-08-12 Update 134-acht-streuhuetten-saniert.Rmd**:  (1bdf75d)
- [ ] **2021-08-12 Update 125-wk-etappe1.Rmd**: Bitte nach neuer Unter-Rubrik "Wirkungskontrolle" verschieben (a31bf42)
- [ ] **2021-08-12 Add files via upload**: bitte an entsprechender Stelle verlinken (16a586e)
- [ ] **2021-08-12 Update 125-wk-etappe1.Rmd**:  (7c3a508)
- [ ] **2021-08-12 Update 118-ueberarbeitete-karten-fuer-massnahme.Rmd**:  (f10ad6f)
- [ ] **2021-08-12 Update 120-drei-streuhuetten-sind-saniert.Rmd**:  (9915ca4)
- [ ] **2021-08-12 Update 110-feldscheunen-sanierung-2018-03.Rmd**:  (5529a4a)
- [ ] **2021-08-12 Update 101-feldscheunen-sanierung-2017-10.Rmd**:  (b035e9d)
- [ ] **2021-08-12 Update 112-beispiel-mosli.Rmd**: Bitte nach neuer Unter-Rubrik "Wirkungskontrolle" verschieben (1362605)
- [ ] **2021-08-11 Update 97-souvenir-2016-7.Rmd**:  (70dfe50)
- [ ] **2021-08-11 Update 124-souvenir-dez-2019.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (fb7e03f)
- [ ] **2021-08-11 Update 94-feldscheunen-sanierung-2016-7.Rmd**:  (27c10c1)
- [ ] **2021-08-11 Update 100-massnahmenstande-ende-2016.Rmd**:  (f4b3c54)
- [ ] **2021-08-11 Add files via upload**:  (a2b16d0)
- [ ] **2021-08-11 Update 129-zwischenbericht-2019.Rmd**: bitte auch mit yumpu einbetten gemäss embed code (8cb99dd)
- [ ] **2021-08-11 Update 121-zwischenbericht-2018.Rmd**: bitte auch mit yumpu einbetten gemäss embed code (7b6e3cd)
- [ ] **2021-08-11 Update 121-zwischenbericht-2018.Rmd**:  (288ea9c)
- [ ] **2021-08-11 Update 109-zwischenbericht-2017-von-phase-2.Rmd**: bitte auch mit yumpu einbetten gemäss embed code (d2630d8)
- [ ] **2021-08-11 Update 99-zwischenbericht-2015-16-von-phase-2.Rmd**: bitte auch mit yumpu einbetten gemäss embed code (3a50d19)
- [ ] **2021-08-11 Add files via upload**: an entsprechender Stelle verlinken (57272a1)
- [ ] **2021-08-11 Update 121-zwischenbericht-2018.Rmd**: bitte auch mit yumpu einbetten gemäss embed code (2712ee7)
- [ ] **2021-08-11 Add files via upload**: Verlinkung an entsprechender Stelle im Text (2c0b825)
- [ ] **2021-08-11 Update 99-zwischenbericht-2015-16-von-phase-2.Rmd**:  (926c48f)
- [ ] **2021-08-11 Update 64-phase-1-schlussbericht.Rmd**:  (1732459)
- [ ] **2021-08-11 Update 77-100-massnahmen-realisiert.Rmd**:  (78dfcc1)
- [ ] **2021-08-11 Update 80-massnahmen-sind-nachweislich-attrakti.Rmd**: Bitte nach neuer Unter-Rubrik "Wirkungskontrolle" verschieben (f47e72a)
    git log --all --author wicoz --pretty=format:"- [ ] **%as %s**: %b (%h)" | xclip -selection

- [ ] **2021-08-11 Update 65-dokumentation-massnahmen-umsetzung.Rmd**: bitte diesen Beitrag löschen (97de387)
- [ ] **2021-08-11 Update 60-massnahmen-die-wir-finanziell-unterst.Rmd**:  (6f503fb)
- [ ] **2021-08-11 Update 106-wir-unterstuetzen-die-instanstellung.Rmd**: hier Beitrag löschen. 
Nicht aber derselbe unter "Welche Massnahmen!" (ca8833b)
- [ ] **2021-08-11 Add files via upload**:  (92c6b67)
- [ ] **2021-08-11 Update 63-unsere-massnahmen-mit-landwirtschaftl.Rmd**:  (2de0db4)
- [ ] **2021-08-11 Update 61-bonus-system-zur-verguetung-von-massn.Rmd**:  (d5afb4b)
- [ ] **2021-08-11 Update 20-anpacken.Rmd**: Diesen Beitrag löschen (ce6a683)
- [ ] **2021-08-11 Update 66-beschrieb-umsetzungsphase.Rmd**:  (7a46809)
- [ ] **2021-08-11 Update 3-ziele-des-projekts-wiesel-co-am-zimmer.Rmd**:  (7dbfcaf)
- [ ] **2021-08-11 Update 11-das-wieselfoerderprojekt-der-gemeinde.Rmd**:  (1d5a31b)
- [ ] **2021-08-11 Update 11-das-wieselfoerderprojekt-der-gemeinde.Rmd**:  (9f8d463)
- [ ] **2021-08-11 Update 66-beschrieb-umsetzungsphase.Rmd**:  (40812f5)
- [ ] **2021-08-11 Update 66-beschrieb-umsetzungsphase.Rmd**:  (334f75a)
- [ ] **2021-08-11 Add files via upload**:  (a06bfb7)
- [ ] **2021-08-11 Update 3-ziele-des-projekts-wiesel-co-am-zimmer.Rmd**:  (fbcda50)
- [ ] **2021-08-11 Update 2-motivation.Rmd**:  (a5ae757)
- [ ] **2021-08-11 Add files via upload**:  (7e11fe7)
- [ ] **2021-08-11 Add files via upload**:  (92f069d)
- [ ] **2021-08-11 Update 11-das-wieselfoerderprojekt-der-gemeinde.Rmd**:  (b3741bf)
- [ ] **2021-08-11 Update 2-motivation.Rmd**:  (eaf9cf6)
- [ ] **2021-08-11 Update 27-die-traegerschaft-wir-stellen-uns-vor.Rmd**:  (3aaa363)
- [ ] **2021-08-02 Update 114-hinweise-haufen.Rmd**:  (ed67815)
- [ ] **2021-08-02 Update viel-glck-auf-der-wieselpirsch.Rmd**:  (fda9af5)
- [ ] **2021-08-02 Update viel-glck-auf-der-wieselpirsch.Rmd**:  (9e2a538)
- [ ] **2021-08-02 Update 2-motivation.Rmd**:  (e66104a)

**Comment by wicoz** [comment]
Nur Update-Hinweise erhalten, die damit zu tun haben, dass ein Beitrag in eine neue Rubrik verschoben werden muss

**Comment by wicoz** [comment]
Folgend jene Updates, die mit dem Verschieben nach Rubriken zu tun haben. Deine ursprünliche Sammlung hatte ich begonnen zu editieren (anderweitige updates daraus löschen). Mir wurde dann aber mulmig, weil diese anderweitigen updates von 2021-08-11 noch zu einem guten Teil nicht erledigt sind - so zB das am Telefon erwähnte Löschen des Kontaktformulars und noch viele mehr. Bitte diese nicht übergehen und möglichst bald angehen, damit ich die Sache auch noch im Gedächtnis habe. 

nun also die Liste mit den "Verschieben"-updates  - danke schonmal! 

- [ ] **2021-08-12 Update 2021-03-14-128-wicoz-bilanz.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (ea79eca)
- [ ] **2021-08-12 Update 2020-01-26-123-aktionstage-feb-20.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (7bb4e44)
- [ ] **2021-08-12 Update 2019-11-29-122-aktionstage-dez-19.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (ded4c59)
- [ ] **2021-08-12 Update 2019-10-16-119-exkursion-klein-ganz-gross.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (45cfaa4)
- [ ] **2021-08-12 Update 2019-10-16-116-workshop-wuehlmaeuse-im-gr.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (66d6dd4)
- [ ] **2021-08-12 Update 2019-03-08-113-pflanzung-wolfbuehl-maerz2.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (24d9865)
- [ ] **2021-08-12 Update 2017-11-07-102-exkursion-12-nov-resultate.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (fe193c9)
- [ ] **2021-08-12 Update 2017-04-03-96-sonderausstellung-wildnispa.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (be145b4)
- [ ] **2021-08-12 Update 2017-04-03-95-aktionstage-april-2017.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (5ffb753)
- [ ] **2021-08-12 Update 2017-02-15-111-strukturenbau-14-april.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben

ergänztes PDF lade ich auch noch via "upload file" hoch (6a5fe8a)
- [ ] **2021-08-12 Update 2017-02-15-81-aktionstage-februar-2017.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (b03fe4b)
- [ ] **2021-08-12 Update 2017-01-30-79-hecken-und-waldrandpflegeku.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (01d88bf)

- [ ] **2021-08-12 Update 2017-01-26-29-erste-moeglichkeiten-zum-mi.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (b639909)
- [ ] **2021-08-12 Update 2016-03-08-71-aststrukturen-bauen-sa-12-m.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (1242e5b)

- [ ] **2021-08-12 Update 2016-03-07-74-aktionstage-april-2016.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (db02705)
- [ ] **2021-08-12 Update 2016-02-26-70-mit-ferienpass-kleinstruktu.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (c66a80c)
- [ ] **2021-08-12 Update 2016-01-28-68-einladung-zur-infoveranstal.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (4e5023c)
- [ ] **2021-08-12 Update 2014-01-29-16-exkursion-kleinraubtiere-ke.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (8b4b9c8)
- [ ] **2021-08-12 Update 2014-01-29-18-unser-faltblatt.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (5f80785)
- [ ] **2021-08-12 Update pressespiegel.Rmd**: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (dfb9f06)
- [ ] **2021-08-12 Update gesamtschau-der-wirkungskontrolle.Rmd**: Bitte nach neuer Unter-Rubrik "Wirkungskontrolle" verschieben (51e2b6a)
- [ ] **2021-08-12 Update 112-beispiel-mosli.Rmd**: Bitte nach neuer Unter-Rubrik "Wirkungskontrolle" verschieben (1362605)
- [ ] **2021-08-11 Update 124-souvenir-dez-2019.Rmd**: Bitte nach Unter-Rubrik "Praktischer Naturschutz" (ex-Anpacken) verschieben (fb7e03f)
- [ ] **2021-08-11 Update 80-massnahmen-sind-nachweislich-attrakti.Rmd**: Bitte nach neuer Unter-Rubrik "Wirkungskontrolle" verschieben (f47e72a)
    git log --all --author wicoz --pretty=format:"- [ ] **%as %s**: %b (%h)" | xclip -selection

**Comment by wicoz** [comment]
ich befürchte, dass durch das Verschieben obiger Beiträge und damit die Änderung des Pfades auch die internen Links in anderen Beiträgen angepasst werden müssen. 

-> wie gehen wir dort am besten vor? 
Vorschlag: 
ich mache die notwendigen Änderungen in den codes. 
Würdest Du dann aber diese sogleich aufs Funktionieren prüfen und allfällige Fehler korrigieren? 
Sonst muss ich dann die Links der ganzen Website nochmals durchprüfen... .

ODER: 
blüht das uns so oder so nochmals wenn die Page umgeleitet wird auf wieselundco.ch??

**Comment by wicoz** [comment]
Unter-Rubrik "Beobachtungen" fehlt noch 

> FASZINATION KLEINRAUBTIERE
> Unsere Zielarten
> Mensch und Wiesel
> Beobachtungen STATT Beobachtung melden

Zu den bisherigen Beiträgen hab ich ja am 2021-08-11 auch diverse updates gemacht.

**Comment by ratnanil** [comment]
ich verstehe nicht mehr was hier gemacht werden muss... können wir das ganze etwas aufdröseln, vereinfachen, entschlacken? Lass uns  telefonieren

**Comment by wicoz** [comment]
Also mir scheint hoch prioritär, dass Du die obigen "verschieben-updates" ausführst. 
Danach kann ich erst die internen Weblinks korrigieren, die mit den verschobenen Beiträgen zusammenhängen. 
Ich werde eh nochmals die ganze page strählen müssen, nachdem Du mir das mit dem "relativen Pfad" #6 mitgeteilt hast. 
Das wird nochmals ein rechter Brocken Arbeit.

**Comment by ratnanil** [comment]
beiträge sollten verschoben sein, kannst du mal checken?

**Comment by wicoz** [comment]
Klasse!

2 bleiben noch

Verschieben nach WK
https://wieselundco.github.io/website/projekt-resultate/125-wk-etappe1/

Verschieben nach Resultate
https://wieselundco.github.io/website/infoveranstaltungen/pressespiegel/

**Comment by ratnanil** [comment]
> Verschieben nach WK
> https://wieselundco.github.io/website/projekt-resultate/125-wk-etappe1/
> 
> Verschieben nach Resultate
> https://wieselundco.github.io/website/infoveranstaltungen/pressespiegel/

erledigt

**Comment by wicoz** [comment]
2021-08-12 Update 2017-01-30-79-hecken-und-waldrandpflegeku.Rmd: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (01d88bf)


und 

 2021-08-12 Update 2014-01-29-16-exkursion-kleinraubtiere-ke.Rmd: Bitte nach neuer Unter-Rubrik "Öffentlichkeitsarbeit" verschieben (8b4b9c8)

sind noch zu verschieben nach Infoveranstaltungen; 
relative Links darauf passe ich entsprechend an

**Comment by ratnanil** [comment]
bitte kontrollieren

**Comment by wicoz** [comment]
Der da https://wieselundco.github.io/website/news/2017-01-30-79-hecken-und-waldrandpflegeku/ muss nach https://wieselundco.github.io/website/Infoveranstaltungen.html

https://wieselundco.github.io/website/infoveranstaltungen/107-hecken-und-waldrandaufwertungen/  muss wieder zurück nach https://wieselundco.github.io/website/Welche-Massnahmen.html

**Comment by ratnanil** [comment]
mist.. so?

**Comment by wicoz** [comment]
danke, bestens!
