### ISSUE TITLE
Who-is-who besser formatieren

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#45]
Kannst Du da noch eine Möglichkeit bieten, damit die Zeichnungen grösser angeschaut werden können?

Galerie oder etwas in der Art?

https://wieselundco.github.io/website/faszination-kleinraubtiere-unsere-leitarten/12-who-is-who/

**Comment by ratnanil** [comment]
du könntest die bilder in ein flicker album tun?

**Comment by wicoz** [comment]
Ich glaube es ist am einfachsten, die Tabelle und die kleinen Bildern durch untenstehendes Bild zu ersetzen, das ich dir auch unter <> Code rauflade. 
Siehts gut aus?

Dann ergänze ich noch einen Verweis mit Link in <>Code
![zielarten_cigler](https://user-images.githubusercontent.com/49158554/129403256-98bb4d87-9293-4530-bde9-63ee70300766.PNG)

**Comment by ratnanil** [comment]
ist geupdated

https://wieselundco.netlify.app/faszination-kleinraubtiere-unsere-leitarten/12-who-is-who/

**Comment by wicoz** [comment]
Sehr schön!

habe im rmd noch einige Textpassagen angepasst und zwei PDFs verlinkt. 
die files hab ich auch raufgeladen nach besprochener Methode (add file).

bitte kompilieren

**Comment by ratnanil** [comment]
bitte kontrollieren

**Comment by wicoz** [comment]
perfekt - unter https://wieselundco.netlify.app/unsere-zielarten stimmt übrigens auch die Reihenfolge der Beiträge, kam also nicht überall durcheinander. vgl. #62
