### ISSUE TITLE
Gallerie einbauen in https://wieselundco.github.io/website/wissenschaft-externe-projekte/126-mammaliabox/ 

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#46]
hatte gefehlt, hab ich eben erstellt: 

Link https://flic.kr/s/aHsmWoS1da

embed code für Fusszeile
<a data-flickr-embed="true" data-footer="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719671434929" title="MammaliaBox"><img src="https://live.staticflickr.com/65535/51374542584_d29aeeecee_z.jpg" width="640" height="480" alt="MammaliaBox"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

_Originally posted by @wicoz in https://github.com/wieselundco/website/issues/3#issuecomment-897268942_

**Comment by ratnanil** [comment]
erledigt https://wieselundco.github.io/website/wissenschaft-externe-projekte/126-mammaliabox/

**Comment by wicoz** [comment]
sehr gut, 
habe noch kleine Änderung und Wunsch "Ausserdem bitte noch den unnötigen Dateinamen unter der Galerie entfernen. " in <> Code angegeben

**Comment by wicoz** [comment]
i see, der unnötige Dateiname ist wahrscheinlich bedingt durch den falschen embed code (mit Fusszeile!). 

Hier der neue, den ich auch im <code> korrigiert habe.

Bitte prüfen, ob Dateiname unter Galerie weg ist.


<a data-flickr-embed="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719671434929" title="MammaliaBox"><img src="https://live.staticflickr.com/65535/51374542584_d29aeeecee_z.jpg" width="640" height="480" alt="MammaliaBox"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

**Comment by ratnanil** [comment]
erledigt, dateinamen sind weg (bzw. nur noch in der gallerie drin)
