### ISSUE TITLE
Gallerie einbauen in http://www.wieselundco.ch/faszination-kleinraubtiere/unsere-leitarten/13-die-familie-der-marderartigen

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#47]
Galerie fehlte, hab ich eben erstellt: 
https://flic.kr/s/aHsmWpP6PZ

embed code Fusszeile: 
<a data-flickr-embed="true" data-footer="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719682184987" title="Marderartige"><img src="https://live.staticflickr.com/65535/51373796686_a8c5c24048_w.jpg" width="640" height="480" alt="Marderartige"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

_Originally posted by @wicoz in https://github.com/wieselundco/website/issues/3#issuecomment-897345344_

**Comment by ratnanil** [comment]
erledigt

**Comment by wicoz** [comment]
i see, der unnötige Dateiname ist wahrscheinlich bedingt durch den falschen embed code (mit Fusszeile!). 

Hier der neue, den ich auch im <code> korrigiert habe.

Bitte prüfen, ob Dateiname unter Galerie weg ist.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719682184987" title="Marderartige"><img src="https://live.staticflickr.com/65535/51373796686_a8c5c24048_w.jpg" width="640" height="480" alt="Marderartige"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

**Comment by ratnanil** [comment]
erledigt, dateinamen sind weg (bzw. nur noch in der gallerie drin)
