### ISSUE TITLE
Gallerie funktioniert nicht https://wieselundco.github.io/website/projekt-massnahmen/107-hecken-und-waldrandaufwertungen/

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#48]
da war nur ein einziges Bild drin. 
habe die restlichen ergänzt. 
Die Gallerieanzeige funktioniert aber nicht. 

bitte neu verlinken: 
https://flic.kr/s/aHsmWhr87a

embed code für Fusszeile
<a data-flickr-embed="true" data-footer="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719598681353" title="Heckenpflege Rietwies, Horgen 2016"><img src="https://live.staticflickr.com/65535/51374077633_abc769301a_z.jpg" width="640" height="480" alt="Heckenpflege Rietwies, Horgen 2016"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

**Comment by ratnanil** [comment]
erledigt

**Comment by wicoz** [comment]
1.
eben Strickhof Link aktualisiert auf extern umgeschaltet in <> Code; bitte prüfen.

zwei interne Links funktionieren nicht mehr - kannst du den Pfad korrigieren bitte?

2.
i see, der unnötige Dateiname ist wahrscheinlich bedingt durch den falschen embed code (mit Fusszeile!). 

Hier der neue, den ich auch im <code> korrigiert habe.

Bitte prüfen, ob Dateiname unter Galerie weg ist.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719598681353" title="Heckenpflege Rietwies, Horgen 2016"><img src="https://live.staticflickr.com/65535/51374077633_abc769301a_z.jpg" width="640" height="480" alt="Heckenpflege Rietwies, Horgen 2016"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
