### ISSUE TITLE
3 der fehlenden Beiträge ergänzen

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#49]
Du hast seehr viele Beiträge migriert, so einige sind nicht mitgekommen. 
(wenn wir wiedermal eine Website migrieren, dann machen wir eine Vorbesprechung, ... ; )
Folgende 3 davon sind substantiell im Projektverlauf und sollen darum migriert werden .

**Comment by wicoz** [comment]
ERSTENS 
unter neuer Rubrik INFOVERANSTALTUNGEN

http://wieselundco.ch/news/10-das-projekt/aktueller-stand/48-ein-vielseiter-workshop-mit-reger-teilnahme-wurde-erfolgreich-druchgefuehrt   

thumbnail und Hauptbild: 
![0100a_b_20150131_120_0 2](https://user-images.githubusercontent.com/49158554/129248520-948ddf7b-3cb4-409d-9641-670058850b43.jpg)

Galerie einbetten: 
https://flic.kr/s/aHsmWtyhDZ
embed code
<a data-flickr-embed="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719724560715" title="Workshop Phase 1, Januar 2015"><img src="https://live.staticflickr.com/65535/51374518354_78fc0b94a9.jpg" width="640" height="480" alt="Workshop Phase 1, Januar 2015"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

**Comment by wicoz** [comment]
ZWEITENS unter Rubrik PRAKTISCHER NATURSCHUTZ (EHEMALS ANPACKEN)

http://wieselundco.ch/news/10-das-projekt/aktueller-stand/53-kleinstrukturen-der-pilotmassnahme-erstellt

thumnail und Hauptbild: 
![IMG_0100](https://user-images.githubusercontent.com/49158554/129250212-78f1517c-a97e-49c4-b637-3eef70846bdc.JPG)


bitte Galerie einbetten: 
https://flic.kr/s/aHsmWoT95R

<a data-flickr-embed="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719671656529" title="Pilotmassnahme Stockenbach, März 2015"><img src="https://live.staticflickr.com/65535/51373924611_88999b8c24_z.jpg" width="640" height="480" alt="Pilotmassnahme Stockenbach, März 2015"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

**Comment by wicoz** [comment]
DRITTENS unter neuer RUBRIK INFOVERANSTALTUNGEN

http://wieselundco.ch/news/10-das-projekt/aktueller-stand/43-rueckblick-auf-die-wildnissafari-2014

thumnail und hauptbild: 
![ZG7N9682_Bildgröße ändern](https://user-images.githubusercontent.com/49158554/129252764-7b0bcf6a-c08f-4032-93dc-d647d324280c.JPG)


bitte Galerie einbetten: 
https://flic.kr/s/aHsmWtA8VN

<a data-flickr-embed="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719724921580" title="Wildnissafari, Besucherzentrum Sihlwald, 2014"><img src="https://live.staticflickr.com/65535/51374971200_7e90b9a3fa_z.jpg" width="640" height="480" alt="Wildnissafari, Besucherzentrum Sihlwald, 2014"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

**Comment by ratnanil** [comment]
in 3 issues aufgeteilt
