### ISSUE TITLE
Rubrik "Infoveranstaltungen", nicht verwirren lassen durch "Öffentlichkeitsarbeit"

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#50]
Als ich gestern in diversen Beiträgen (v.a. aus News) in <Code> kleinere Anpassungen gemacht hatte, beschrieb ich vor dem Absenden im description Feld teilweise die gewünschte Verschiebung nach Unter-Rubrik "xy". 

Ich glaube, ich hatte da versehentlich mehrmals  geschrieben, aber die Rubrik "Infoveranstaltungen" gemeint.
-> Rubrik "Infoveranstaltungen" ist der richtige Name und nicht "Öffentlichkeitsarbeit"

**Comment by ratnanil** [comment]
das betriff #44 oder?
