### ISSUE TITLE
ERSTENS

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/website#51]
ERSTENS 
unter neuer Rubrik INFOVERANSTALTUNGEN

http://wieselundco.ch/news/10-das-projekt/aktueller-stand/48-ein-vielseiter-workshop-mit-reger-teilnahme-wurde-erfolgreich-druchgefuehrt   

thumbnail und Hauptbild: 
![0100a_b_20150131_120_0 2](https://user-images.githubusercontent.com/49158554/129248520-948ddf7b-3cb4-409d-9641-670058850b43.jpg)

Galerie einbetten: 
https://flic.kr/s/aHsmWtyhDZ
embed code
<a data-flickr-embed="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719724560715" title="Workshop Phase 1, Januar 2015"><img src="https://live.staticflickr.com/65535/51374518354_78fc0b94a9.jpg" width="640" height="480" alt="Workshop Phase 1, Januar 2015"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

_Originally posted by @wicoz in https://github.com/wieselundco/website/issues/49#issuecomment-897870414_

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/infoveranstaltungen/2015-02-01-ein-vielseiter-workshop-mit-reger-teilnahme/

**Comment by wicoz** [comment]
danke, nun gilt es noch einige Beiträge, hierhin zu verschieben gemäss updates/comments in #44
