### ISSUE TITLE
ZWEITENS unter Rubrik PRAKTISCHER NATURSCHUTZ (EHEMALS ANPACKEN)

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/website#52]
ZWEITENS unter Rubrik PRAKTISCHER NATURSCHUTZ (EHEMALS ANPACKEN)

http://wieselundco.ch/news/10-das-projekt/aktueller-stand/53-kleinstrukturen-der-pilotmassnahme-erstellt

thumnail und Hauptbild: 
![IMG_0100](https://user-images.githubusercontent.com/49158554/129250212-78f1517c-a97e-49c4-b637-3eef70846bdc.JPG)

bitte Galerie einbetten: 
https://flic.kr/s/aHsmWoT95R

<a data-flickr-embed="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719671656529" title="Pilotmassnahme Stockenbach, März 2015"><img src="https://live.staticflickr.com/65535/51373924611_88999b8c24_z.jpg" width="640" height="480" alt="Pilotmassnahme Stockenbach, März 2015"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

_Originally posted by @wicoz in https://github.com/wieselundco/website/issues/49#issuecomment-897876361_

**Comment by ratnanil** [comment]
erledigt 

https://wieselundco.netlify.app/mithelfen-anpacken-mithelfen/2015-09-01-kleinstrukturen-der-pilotmassnahme-erstellt/

stimmt das datum etwa?

**Comment by wicoz** [comment]
danke, nun gilt es noch einige Beiträge, hierhin zu verschieben gemäss updates/comments in #44 

Datum passt nicht schlecht würde ich noch anpassen, falls es Sinn macht.
