### ISSUE TITLE
DRITTENS unter neuer RUBRIK INFOVERANSTALTUNGEN

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/website#53]
DRITTENS unter neuer RUBRIK INFOVERANSTALTUNGEN

http://wieselundco.ch/news/10-das-projekt/aktueller-stand/43-rueckblick-auf-die-wildnissafari-2014

thumnail und hauptbild: 
![ZG7N9682_Bildgröße ändern](https://user-images.githubusercontent.com/49158554/129252764-7b0bcf6a-c08f-4032-93dc-d647d324280c.JPG)

bitte Galerie einbetten: 
https://flic.kr/s/aHsmWtA8VN

<a data-flickr-embed="true" href="https://www.flickr.com/photos/193617721@N08/albums/72157719724921580" title="Wildnissafari, Besucherzentrum Sihlwald, 2014"><img src="https://live.staticflickr.com/65535/51374971200_7e90b9a3fa_z.jpg" width="640" height="480" alt="Wildnissafari, Besucherzentrum Sihlwald, 2014"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

_Originally posted by @wicoz in https://github.com/wieselundco/website/issues/49#issuecomment-897889587_

**Comment by ratnanil** [comment]
> Möchten Sie per Mail informiert werden? Dann melden Sie sich hier für den Newsletter an!

diesen satz am ende habe ich rausgelöscht

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/infoveranstaltungen/2014-08-30-rckblick-auf-die-wildnissafari-2014/

**Comment by wicoz** [comment]
bestens, danke
