### ISSUE TITLE
Wichtige update-Kommentare

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#54]
aus #44 
einige wenige davon hatte ich schon gelöscht; den Rest habe ich bereinigt, so dass nur noch jene dastehen, die Du nicht schon beim Kompilieren bearbeitet hast/wirst (hoffentlich):

- [x] **2021-08-12 Update 2016-04-08-72-teamaktion-mit-wiesel-co-am.Rmd**: Hier bitte löschen, aber nicht derselbe Beitrag unter"Praktischer Naturschutz" (ex-Anpacken) (8f86a57)
- [x] **2021-08-12 Update 24-kontakt.Rmd**: ist das für Dich so ok mit deiner Kontaktangabe? (3c7ef35)
- [x] **2021-08-12 Update 39-zur-interaktiven-karte.Rmd**: die eigentliche Karte ist zwar noch aktiv und muss es vorübergehend noch bleiben, aber der Text ist hier bereits angepasst. 
- [x] **2021-08-12 Delete 32-eine-beobachtung-melden-2.Rmd**:  (ee9264c)
- [x] **2021-08-12 Delete 40-zum-kontaktformular.Rmd**:  (e2f3852)
- [x] **2021-08-12 Delete 22-kontaktformular.Rmd**:  (509b5a9)
- [x] **2021-08-12 Delete 21-sponsoring.Rmd**:  (82a5bee)
- [x] **2021-08-12 Delete 20-anpacken.Rmd**:  (7247b53)
- [x] **2021-08-12 Update 131-nistkammer-monitoring.Rmd**: funktioniert das unterste Bild nun? (0b767de)
- [x] **2021-08-12 Update 85-stand-der-entwicklung.Rmd**: funktioniert Bild jetzt? (da6f8f6)
- [x] **2021-08-11 Update 129-zwischenbericht-2019.Rmd**: bitte auch mit yumpu einbetten gemäss embed code (8cb99dd)
- [x] **2021-08-11 Update 121-zwischenbericht-2018.Rmd**: bitte auch mit yumpu einbetten gemäss embed code (7b6e3cd)
- [x] **2021-08-11 Update 109-zwischenbericht-2017-von-phase-2.Rmd**: bitte auch mit yumpu einbetten gemäss embed code (d2630d8)
- [x] **2021-08-11 Update 99-zwischenbericht-2015-16-von-phase-2.Rmd**: bitte auch mit yumpu einbetten gemäss embed code (3a50d19)

- [x] **2021-08-11 Update 65-dokumentation-massnahmen-umsetzung.Rmd**: bitte diesen Beitrag löschen (97de387)
- [x] **2021-08-11 Update 106-wir-unterstuetzen-die-instanstellung.Rmd**: hier Beitrag löschen. 
Nicht aber derselbe unter "Welche Massnahmen!" (ca8833b)
- [x] **2021-08-11 Update 20-anpacken.Rmd**: Diesen Beitrag löschen (ce6a683)

**Comment by ratnanil** [comment]
> 2021-08-11 Update 129-zwischenbericht-2019.Rmd: bitte auch mit yumpu einbetten gemäss embed code (8cb99dd)

bitte noch überprüfen: 

- https://wieselundco.netlify.app/projekt-resultate/129-zwischenbericht-2019/
- https://wieselundco.netlify.app/projekt-resultate/121-zwischenbericht-2018/
- https://wieselundco.netlify.app/projekt-resultate/109-zwischenbericht-2017-von-phase-2/
- https://wieselundco.netlify.app/projekt-resultate/99-zwischenbericht-2015-16-von-phase-2/

> 2021-08-11 Update 106-wir-unterstuetzen-die-instanstellung.Rmd: hier Beitrag löschen.
Nicht aber derselbe unter "Welche Massnahmen!"

so?

**Comment by wicoz** [comment]
very nice!
Habe im rmd von  https://wieselundco.github.io/website/projekt-resultate/99-zwischenbericht-2015-16-von-phase-2/ noch ein Bild rausgelöscht -> bitte kompilieren

**Comment by ratnanil** [comment]
bitte kontrollieren

**Comment by wicoz** [comment]
passt!
