### ISSUE TITLE
Unter-Rubrik "Beobachtungen" fehlt noch

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/website#55]
Unter-Rubrik "Beobachtungen" fehlt noch 

> FASZINATION KLEINRAUBTIERE
> Unsere Zielarten
> Mensch und Wiesel
> Beobachtungen STATT Beobachtung melden

Zu den bisherigen Beiträgen hab ich ja am 2021-08-11 auch diverse updates gemacht.

_Originally posted by @wicoz in https://github.com/wieselundco/website/issues/44#issuecomment-898714659_

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/beobachtungen

**Comment by wicoz** [comment]
Merci, ich habe einige Anpassungen/Korrekturen gemacht, bitte kompilieren.

**Comment by ratnanil** [comment]
bitte kontrollieren

**Comment by wicoz** [comment]
nach dem Kompilieren, bitte prüfen, ob unter https://wieselundco.github.io/website/mithelfen-anpacken-beobachtung/33-eine-beobachtung-melden-3/ der letzte Satz nun normal formatiert ist

**Comment by ratnanil** [comment]
bitte überprüfen

**Comment by wicoz** [comment]
super!
