### ISSUE TITLE
 Hyperlinks im "Description" field

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/website#56]
Leider kannst du keine hyperlinks im description feld haben. das sieht dann in der liste folgendermassen aus.. kannst du die noch beheben?

![image](https://user-images.githubusercontent.com/12532091/129984384-17d42fe5-647f-4a59-82d7-c09c974b0d21.png)

**Comment by ratnanil** [comment]
![image](https://user-images.githubusercontent.com/12532091/129986439-34ba985a-796c-44a0-bfa0-76b9a68153d0.png)

**Comment by wicoz** [comment]
ufff... 
ich warte ab, bis #44 erledigt ist

**Comment by ratnanil** [comment]
![image](https://user-images.githubusercontent.com/12532091/130583854-40d1086e-bd95-487a-a662-b4758399ef9c.png)

**Comment by wicoz** [comment]
erledigt
