### ISSUE TITLE
Beitrag Motivation bereinigen

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#59]
es macht hier keinen Sinn, dass ich im rmd etwas mache. 
Sieh Dir bitte das preview (Bild fehlt) und den Hauptbeitrag an - da ist einige zunderobsi. 
Magst Du dies bitte bereinigen?

**Comment by ratnanil** [comment]
https://wieselundco.netlify.app/projekt-ausgangslage/2-motivation/

**Comment by wicoz** [comment]
merci! ich bereinige dann noch #56
