### ISSUE TITLE
webseite auf wieselundco.ch umleiten

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#6]
sobald sie steht...

**Comment by ratnanil** [comment]
welche issues müssen noch erledigt werden, bevor wir die webseite auf wieselundco.ch umleiten?

**Comment by wicoz** [comment]
> welche issues müssen noch erledigt werden, bevor wir die webseite auf wieselundco.ch umleiten?

- [ ] das Überarbeiten der Texte, Formatierung prüfen etc durch mich. Wie geschmeidig ich das selber machen kann, werde ich sehen... 
- [ ] Beitrag WK Durchlass Zugerstrasse (sollte ich am Wochenende fertig haben, auch abhängig von Sabina und kt. Tiefbauamt) 
- [ ] Beitrag WK Ah/Wq etc. (da weiss ich grad nicht, ob ich von Dir schon Bescheid hinsichtlich Abschluss)
- [ ] Beitrag Feldscheunen Resultate
- [ ] ...

Diese Dinge hoffe ich alle in den nächsten Tage erledigen zu können...  Ich bin eigentlich wenn immer möglich dran... 


was noch relevant ist: 
Kannst Du auf github auch Beiträge erstellen, danach aber vorerst verbergen bzw. zu bestimmtem Datum veröffentlichen?
Dann können wir die weiteren, voraussichtlich letzten Beiträge (Videos, Schlussbericht, NNZ) nämlich auch schon generieren vor dem 15. August.


Ich plane nämlich 2 Newsletter: 

1. wenn möglich vor 15. August: 
Bericht WK Durchlass, Bericht WK Ah/Wq, Wieselpirsch, Feldscheunen... 
2. im September: 
Videos, Schlussbericht, NNZ, Benachrichtigung Plattform Sichtungsmeldung (für Meldungen inaktiv, neu CSCF), ...

**Comment by ratnanil** [comment]
>  Kannst Du auf github auch Beiträge erstellen, danach aber vorerst verbergen bzw. zu bestimmtem Datum veröffentlichen?

doch das geht, man muss `draft: true` in den titel schreiben (siehe [hier](https://rstudio.github.io/distill/blog_workflow.html#managing-drafts))

**Comment by wicoz** [comment]
super, ich melde mich wenn so einer steht, um dies von Dir verifizieren zu lassen

**Comment by wicoz** [comment]
In Hinsicht auf den kommenden, zweitletzten Newsletter, den ich am Erstellen bin: 
Im Pfad unserer Website wird nach dem Umleiten einfach ".github.io" durch ".ch" ersetzt, richtig?

Kann ich davon ausgehen, dass die internen Links in den Beiträgen, die jetzt github.io enthalten, automatisch umgeleitet werden? Sicher/unsicher?
Das ist ziemlich relevant für unsere kommenden Aufwände/Kosten... 

Ich hoffe, wir packen die Fertigstellung und Umleitung spätestens bis einige Tage vor dem Plenum vom 25.8...

**Comment by ratnanil** [comment]
> Im Pfad unserer Website wird nach dem Umleiten einfach ".github.io" durch ".ch" ersetzt, richtig?

genau

> Kann ich davon ausgehen, dass die internen Links in den Beiträgen, die jetzt github.io enthalten, automatisch umgeleitet werden? Sicher/unsicher?

solange wir relative pfade benutzen, wird die umleitung funktionieren.

- relativer pfad.` [sehen sie hier](/projekt/ueberuns.html)`
- absoluter pfad. `[sehen sie hier](www.wieselundco.github.io/projekt/ueberuns.html)`

**Comment by wicoz** [comment]
> solange wir relative pfade benutzen, wird die umleitung funktionieren.

relativer pfad. [sehen sie hier](/projekt/ueberuns.html)
absoluter pfad. [sehen sie hier](www.wieselundco.github.io/projekt/ueberuns.html)

Das ist eine äusserst wichtige Info.

Wie verhält sich denn das mit Dateien, wie PDF's? 
Da gibt es zB unter https://wieselundco.netlify.app/ausgangslage-und-ziele diverse Dateien, die absolut verlinkt sind... 

Das Umschreiben in relative Pfade gibt noch eine Menge Fleissarbeit für mich und die Voraussetzung, um damit zu beginnen ist die Verschiebung der Beiträge #44 Sonst muss ich am Schluss alles nochmals durchgehen. 

Ich möchte dies vor dem Plenum vom Mittwoch erledigen, damit wir Kostenwahrheit haben!

**Comment by wicoz** [comment]
machen wir das, wenn wir beide gleichzeitig reagieren können? 

Donnerstag ab 20 Uhr hab ich wieder Zeit. 
Dann wahrscheinlich wieder Sonntag/Montagmorgen und -abend, Dienstag... 

-> Bitte Termin durchgeben

**Comment by ratnanil** [comment]
mittlerweile zeigt http://wieselundco.ch/ auf die neue website, nur funktioniert https noch nicht

**Comment by ratnanil** [comment]
jetzt geht auch https
