### ISSUE TITLE
Links "Artikel bearbeiten"

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#61]
Diese sind in gewissen Beiträgen vorhanden https://wieselundco.netlify.app/projekt-ausgangslage/66-beschrieb-umsetzungsphase/, in anderen nicht. 

Dies müssen dann noch weg, bevor wir die Page umleiten.

**Comment by ratnanil** [comment]
erledigt

**Comment by wicoz** [comment]
Ich muss die einzelnen Beiträge im Rahmen von #56 und #44 eh nochmals durchgehen. 
Dann werde ich darauf achten, ob alle "Artikel bearbeiten" weg sind. 

zufällig gesehen, dass noch nicht erledigt unter
https://wieselundco.netlify.app/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/

**Comment by wicoz** [comment]
bei obigem Feldscheunenbeitrag hast Du dies wohl bereits entfernt, danke. 

hier noch, bitte: 

https://wieselundco.github.io/website/news/2017-01-30-79-hecken-und-waldrandpflegeku/

**Comment by ratnanil** [comment]
erledigt

**Comment by wicoz** [comment]
bestens, danke
