### ISSUE TITLE
WK-Beitrag kopieren nach News

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#63]
https://wieselundco.github.io/website/wirkungskontrolle/2021-08-12-gesamtschau-der-wirkungskontrolle/

sonst keine Ergänzungen zu #44, ausser verstecken von #42 und #43

**Comment by ratnanil** [comment]
https://wieselundco.github.io/website/news/2021-08-12-gesamtschau-der-wirkungskontrolle/

**Comment by wicoz** [comment]
super
