### ISSUE TITLE
Team in Aktion Haupttext

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#65]
https://wieselundco.github.io/website/mithelfen-anpacken-mithelfen/75-teamtraining-mit-wiesel-co-am-zimmerb/
hat rechts auch so ein Schieber-Ding drin; 

![image](https://user-images.githubusercontent.com/49158554/130699321-42f54ef8-cd6e-4e09-9b2e-c6d969ab1384.png)

**Comment by ratnanil** [comment]
bitte in Zukunft https://github.com/wieselundco/website/issues/18#issuecomment-891670136 beachten! 

> es brauch jeweils 1 Leerzeile, wobei die zeilen mit 1 Tab oder zwei Leerschlägen eingerückt beginnen müssen.
