### ISSUE TITLE
Mitwirken Winter 2017 formatieren

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#67]
https://wieselundco.github.io/website/mithelfen-anpacken-mithelfen/2017-01-26-29-erste-moeglichkeiten-zum-mi/
hier hats auch den fulltext verrissen und rechts im Haupttext hats so ein Schieber-Ding

**Comment by ratnanil** [comment]
bitte in Zukunft https://github.com/wieselundco/website/issues/18#issuecomment-891670136 beachten! 

> es brauch jeweils 1 Leerzeile, wobei die zeilen mit 1 Tab oder zwei Leerschlägen eingerückt beginnen müssen.
