### ISSUE TITLE
Aktionstage des Winterhalbjahres 2015/6

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#68]
https://wieselundco.github.io/website/mithelfen-anpacken-mithelfen/2016-03-07-74-aktionstage-april-2016/

hier hats auch so ein Schieberding rechts im Haupttext

**Comment by ratnanil** [comment]
bitte in Zukunft https://github.com/wieselundco/website/issues/18#issuecomment-891670136 beachten! 

> es brauch jeweils 1 Leerzeile, wobei die zeilen mit 1 Tab oder zwei Leerschlägen eingerückt beginnen müssen.
