### ISSUE TITLE
Infoveranstaltung Februar formatieren

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#70]
https://wieselundco.github.io/website/infoveranstaltungen/2016-01-28-68-einladung-zur-infoveranstal/

da hats auch so ein Schieber-Ding

**Comment by ratnanil** [comment]
bitte in Zukunft https://github.com/wieselundco/website/issues/18#issuecomment-891670136 beachten! 

> es brauch jeweils 1 Leerzeile, wobei die zeilen mit 1 Tab oder zwei Leerschlägen eingerückt beginnen müssen.
