### ISSUE TITLE
Gemischtes Doppel formatieren

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#71]
https://wieselundco.github.io/website/faszination-kleinraubtiere-mensch-wiesel/8-gemischtes-doppel/

Das Bild im fulltext ist verpixelt

**Comment by wicoz** [comment]
Bei mir ist es immernoch total verpixelt und darunter steht noch "Wasserrinne_43_66_80"

**Comment by ratnanil** [comment]
sollte jetzt gelöst sein

**Comment by wicoz** [comment]
merci!
