### ISSUE TITLE
Exkursion: “Kleinraubtiere kennen keine Grenzen” formatieren

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#72]
https://wieselundco.github.io/website/news/2014-01-29-16-exkursion-kleinraubtiere-ke/
hier hats auch noch so ein Schieberding

**Comment by ratnanil** [comment]
bitte in Zukunft https://github.com/wieselundco/website/issues/18#issuecomment-891670136 beachten! 

> es brauch jeweils 1 Leerzeile, wobei die zeilen mit 1 Tab oder zwei Leerschlägen eingerückt beginnen müssen.
