### ISSUE TITLE
Hosting, Webmail, Moodle

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#73]
http://webmail.wieselundco.ch/login.php ist offline und gmail meldet: 
![image](https://user-images.githubusercontent.com/49158554/132105696-7729f01b-5219-43a7-93f0-332840052108.png)

Ich hab nicht damit gerechnet, dass die Mail down ist nach der Migration... 

Die Vernehmlassugsrunde der Videos läuft über mail@wieselundco.ch. 
(Frist 15. September)

Insofern ist es sehr wichtig, dass da keine Mails verloren gehen!!

Bitte um rasche Rückmeldung.

**Comment by ratnanil** [comment]
ich habe metanet informiert und werde morgen vormittag sicher eine antwort haben

**Comment by wicoz** [comment]
http://webmail.wieselundco.ch/login.php ist online - dankeschön! 
Bin etwas misstrauisch, weil alle Testmails in der Mailbox sind, aber "Test" wiederholt als unzustellbar gemeldet wurde.  Die andern (bisher) nicht. 

Magst Du auch mal noch ein Mail an mail@wieselundco.ch und keller@wieselundco.ch schicken?

**Comment by ratnanil** [comment]
> Die Zustellungsfehler kamen die letzten Male nach jeweils ca 26 Std. herein. 

aber webmail.wieselundco.ch geht doch oder? du kannst doch auch dort testen ob die mails kommen?

**Comment by wicoz** [comment]
Danke, auch dein Testmail hat funktioniert.

**Comment by ratnanil** [comment]
übrigens, wie lange willst du diese Mailadresse behalten? Wenn wir nämlich das hosting der alten website abschalten, verlieren wir auch die mailadressen...

**Comment by wicoz** [comment]
Danke der Nachfrage, Nils- 
Es geht eigentlich nur noch um die kommenden Wochen, in welchen ich auf die Adresse angewiesen bin. (Ende Oktober wär gut)

Weisst Du, wie lange das Hosting über Tizoo (?) noch läuft?
Der letzte Beleg war für 1 Jahr ab 24.6.2020; eine spätere Buchung habe ich nicht gefunden...

[396_Hosting Website_2408.pdf](https://github.com/wieselundco/website/files/7129654/396_Hosting.Website_2408.pdf)

**Comment by ratnanil** [comment]
tizoo brauchen wir nicht mehr,  ich hatte mit Daniel besprochen das er dies Küdigt

**Comment by wicoz** [comment]
über welchen Vertrag läuft denn das webmail bzw. wie lange noch?

**Comment by ratnanil** [comment]
die nächste Erneuerung ist erst 16.05.2022, wir haben also noch zeit.

**Comment by ratnanil** [comment]
uff... moodle migration wäre natürlich auch noch ein Thema

**Comment by wicoz** [comment]
> die nächste Erneuerung ist erst 16.05.2022, wir haben also noch zeit.

merci für die Angabe. Was sind also die nächsten Schritte? Schaltet dann tizoo zu diesem Datum einfach alles ab, d.h es gibt nichts zu tun? 
Wenn nein, würdest Du irgendwann im April/Mai 2022 die nötigen Schritte machen?

**Comment by wicoz** [comment]
> uff... moodle migration wäre natürlich auch noch ein Thema

Momentan läuft das WiCoZ Moodle ja noch. 

Wenn's sein muss/soll, dann können wir ab sofort darauf verzichten, backup brauchts auch nicht. 

Wie lange wird es noch laufen, auch bis 16. Mai?
Dann kann ich dies der Trägerschaft noch mitteilen.

**Comment by ratnanil** [comment]
> Wie lange wird es noch laufen, auch bis 16. Mai? 

ja genau!

**Comment by wicoz** [comment]
merci, hab ich per Moodle mitgeteilt. 
von mir aus kein Handlungsbedarf mehr, oder?
