### ISSUE TITLE
Letzte Anpassungen (Links u.a.)

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#74]
Hab nochmals alles geprüft - teils dürfte es sich mit https://github.com/wieselundco/website/commit/c5588781ceae3cb4b668601ba723f5f11742eb88 decken. 

Untenstehend die Liste meiner Anpassungen. Vor allem als Reminder für mich.

Bitte kompilieren, ... & prüfen:

https://wieselundco.ch/projekt-ausgangslage/3-ziele-des-projekts-wiesel-co-am-zimmer/
- Lebensraum Plakat neu heraufgeladen und Namen entsprechend korrigiert
- ZHAW Link korrigiert
- Tubecam Link korrigiert

https://wieselundco.ch/projekt-ausgangslage/2-motivation/
- file mit entsprechendem Namen neu raufgeladen;  https://wieselundco.ch/projekt-ausgangslage/2-motivation/Plakat.Gefahrdung.pdf

https://wieselundco.ch/projekt-resultate/118-ueberarbeitete-karten-fuer-massnahme/
- [Hier gibt es Hinweise, wie Sie Ihre Beobachtung melden können.](/beobachtungen.html)  (Link war im rmd eigentlich schon richtig - ev. nicht kompiliert?)

https://wieselundco.ch/wirkungskontrolle/2021-08-12-gesamtschau-der-wirkungskontrolle/
und https://wieselundco.ch/mithelfen-anpacken-beobachtung/39-zur-interaktiven-karte/ und https://wieselundco.ch/news/2021-08-12-gesamtschau-der-wirkungskontrolle/
- https://forschung.wieselundco.ch/erfolgskontrolle/ ist momentan? offline

https://wieselundco.ch/wirkungskontrolle/125-wk-etappe1/
- file mit entsprechendem Namen neu raufgeladen: https://wieselundco.ch/wirkungskontrolle/125-wk-etappe1/AnhangC_Patch_Vernetzungsplanung.1.pdf

https://wieselundco.ch/projekt-1-1-untersuetzung/61-bonus-system-zur-verguetung-von-massn/
- Satz Der Vergütungs-Rechner vereinfacht die Berechnung stark - machen Sie sich hier eine Vorstellung davon. und damit Link gelöscht

https://wieselundco.ch/projekt-1-1-untersuetzung/63-unsere-massnahmen-mit-landwirtschaftl/
- 3 PDFs raufgeladen, u.a. Strukturen_DZV_Label_Staeheli2019.pdf (achtung, es gibt ein Doppel mit Leerzeichen im Dateinamen; kann man löschen)

https://wieselundco.ch/wissenschaft-wiesel-co-projekte/86-ermittlung-des-mauswieselvorkommens-m/
- Satz war kursiv: Ob das Mauswiesel aktuell im Bezirk vorkommt ist unklar.

https://wieselundco.ch/wissenschaft-externe-projekte/131-nistkammer-monitoring/
- erster Hyperlink wurde nicht korrekt dargestellt. 

https://wieselundco.ch/projekt-massnahmen/114-hinweise-haufen/
- https://wieselundco.ch/projekt-massnahmen/114-hinweise-haufen/images/dokumente/Holz-Steinhaufen_Empfehlungen_WiCoZ_20190310_red.pdf file raufgeladen

https://wieselundco.ch/projekt-massnahmen/135-winterquartier/
- Link auf Arbeitshilfe_zum_schutz_der_kleinen_saeugetiere.pdf korrigiert

https://wieselundco.ch/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/
- der erste Link führt auf https://wieselundco.ch/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/Resultate.html obwohl in rmd schon jetzt nur (Resultate.html) stand.

https://wieselundco.ch/projekt-massnahmen/107-hecken-und-waldrandaufwertungen/
- file raufgeladen, so dass es auf diesen Link stimmt https://wieselundco.ch/projekt-massnahmen/107-hecken-und-waldrandaufwertungen/Dossier-HeckenWaldrandPflegekurs_20180404.compressed.pdf

https://wieselundco.ch/faszination-kleinraubtiere-wuehlmaeuse/117-info-dossier-und-workshop-2/
- Dossier raufgeladen und Pfad im rmd entsprechend angepasst

https://wieselundco.ch/infoveranstaltungen/2019-10-16-116-workshop-wuehlmaeuse-im-gr/
- [Hier geht’s zur Rubrik “Wühlmäuse im Griff?”(/Wuehlmaeuse.html) Schreibweise angepasst

https://wieselundco.ch/infoveranstaltungen/2014-01-29-18-unser-faltblatt/
- youtube Link vom preview in fulltext verschoben

https://wieselundco.ch/faszination-kleinraubtiere-unsere-leitarten/12-who-is-who/
- 2 files raufgeladen, die auf diese Pfade passen: https://wieselundco.ch/faszination-kleinraubtiere-unsere-leitarten/12-who-is-who/22-Plakat.Iltis_2021.pdf und https://wieselundco.ch/faszination-kleinraubtiere-unsere-leitarten/12-who-is-who/Plakat.Steckbrief.pdf

https://wieselundco.ch/mithelfen-anpacken-beobachtung/39-zur-interaktiven-karte/
- file raufgeladen, das auf diesen Pfad passt https://wieselundco.ch/mithelfen-anpacken-beobachtung/39-zur-interaktiven-karte/21-Plakat.Mauswiesel.Erfassung_2021.pdf

**Comment by ratnanil** [comment]
habe alles neu kompiliert.. kannst du mal prüfen ob deine Änderungen angenommen wurden?

**Comment by wicoz** [comment]
Zwei Dinge haben noch nicht funktioniert: 

https://wieselundco.ch/projekt-massnahmen/114-hinweise-haufen/

Hab den relativen Link zum Dokument https://wieselundco.ch/projekt-massnahmen/114-hinweise-haufen/images/dokumente/Holz-Steinhaufen_Empfehlungen_WiCoZ_20190310_red.pdf im rmd angepasst


https://wieselundco.ch/projekt-massnahmen/62-wir-unterstuetzen-die-instanstellung-/

Hab nun den ersten Link (Über den Fortschritt wird laufend unter der Rubrik Resultate berichtet.) entfernt, weil er immernoch nicht funktionierte.



-> bitte kompilieren und prüfen

**Comment by ratnanil** [comment]
habe beides kompiliert und geprüft, stimmt jetzt
