### ISSUE TITLE
Beiträge kompilieren und veröffentlichen

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#75]
Es handelt sich um 4 verschiedene Beiträge, einer davon unter Resultate und News, d.h. eigentlich 5 Beiträge; unten verlinkt. 

Nebst dem kompilieren bitte den draft-status aufheben!

Nach Möglichkeit am Vormittag bearbeiten, dann kann ich das Ganze nochmals live checken am Mittag und allenfalls noch eine Rückmeldung machen. 

Dankeschön!

https://github.com/wieselundco/website/blob/master/_news/2021-08-11-sehenswerte-projekt-videos-mit-interviews-uvm/sehenswerte-projekt-videos-mit-interviews-uvm.Rmd

https://github.com/wieselundco/website/blob/master/_news/2021-08-11-das-ende-vom-anfang-naturnetz-zimmerberg-wird-aufgebaut/das-ende-vom-anfang-naturnetz-zimmerberg-wird-aufgebaut.Rmd

https://github.com/wieselundco/website/edit/master/_news/2021-09-01-schlussbericht/schlussbericht.Rmd UND https://github.com/wieselundco/website/blob/master/_projekt-resultate/2021-09-01-schlussbericht/schlussbericht.Rmd
Bei letzteren beiden konnte ich das release Datum nicht finden: bitte anpassen auf 20. September 2021
-> date: 09-20-2021

https://github.com/wieselundco/website/blob/master/_ueber-uns/24-kontakt/24-kontakt.Rmd

**Comment by ratnanil** [comment]
erledigt, kannst du kontrollieren?

**Comment by wicoz** [comment]
Oh, leider ist da etwas grundsätzlich in die Hose... ; )

hat das etwas damit zu tun, dass in github "ratnanil merging" steht?

Ich bitte Dich um die Reparatur ensprechend den 3 neuen Issues. 

Da ich am Sonntagmittag in eine Waldprojektwoche verreise, hab ich grad noch ein Haufen zu tun und wär Dir dankbar um baldige Bearbeitung (wenns geht heute Freitag).
Bitte kontrollier dann kurz, ob deine Bearbeitung der issues online angekommen ist.  Im Detail schau ichs mir dann selber gleich noch an. 
So hätten wir am Samstag noch die Gelegenheit zu kleinen Korrekturen, bevor der Newsletter rausgeht.
