### ISSUE TITLE
die beiden Beiträge Schlussbericht reparieren

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#76]
Unbedingt beachten!

1. Die Hauptbeiträge können nicht gefunden werden "page not found" (nur die previews in den beiden Rubriken)
2. der nicht gefundene Link heisst https://wieselundco.ch/news/2021-09-20-schlussbericht/. Es muss der alte Linkname hergestellt werden, bitte selber rekonstruieren, weiss nicht mehr genau. Weil der Schlussbericht wird auch in anderen Beiträgen verlinkt (alter Link!)
3. Ich kann die Beiträge auf github nicht mehr finden!
4. Das release Datum korrigieren: -> date: 09-20-2021
5. Bitte in den beiden Titeln noch einen Leerschlag vor 2021 einfügen

**Comment by ratnanil** [comment]
https://github.com/wieselundco/website/issues/77#issuecomment-932501598
