### ISSUE TITLE
Beitrag Projektabschluss/NNZ reparieren

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#77]
1. Der Hauptbeitrag kann nicht gefunden werden "page not found" (nur das preview unter News ist online)
2. Mindestens das preview Bild funktioniert nicht, ich sehe aber, dass Bilder auf github im Beitrag hinterlegt  & gespeichert sind.

**Comment by ratnanil** [comment]
meinst du  https://wieselundco.ch/projekt-resultate/2021-09-20-schlussbericht/ 
https://wieselundco.ch/news/2021-09-20-schlussbericht/

Die gehen jetzt wieder

**Comment by ratnanil** [comment]
nein du meintest https://wieselundco.ch/news/2021-08-11-das-ende-vom-anfang-naturnetz-zimmerberg-wird-aufgebaut/ oder? der geht jetzt
