### ISSUE TITLE
Beitrag Projekt-Videos reparieren

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#78]
1. Der Hauptbeitrag kann nicht gefunden werden "page not found" (nur das preview unter News ist online)
2. Mindestens das preview Bild funktioniert nicht, ich sehe aber, dass Bilder auf github im Beitrag hinterlegt  & gespeichert sind.

(dieselben Probleme wie bei Projektabschluss/NNZ)

**Comment by ratnanil** [comment]
erledigt

https://wieselundco.ch/news/2021-08-11-sehenswerte-projekt-videos-mit-interviews-uvm/
