### ISSUE TITLE
"Mehr erfahren"

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#8]
"das lässt sich nicht ohne weiteres machen. Man könnte bei jedem Introtext noch manuell den satz hinzufügen "Klicken sie um mehr zu erfahren". Oder man schreibt was entsprechendes in den Header oder Footer der webseite. Für die erste lösung fehlt mir die zeit, ich schau mal ob ich etwas über den header / footer lösen kann"

ev. kann man das Datum in der linken Spalte ersetzen mit "mehr erfahren"?

**Comment by ratnanil** [comment]
> ev. kann man das Datum in der linken Spalte ersetzen mit "mehr erfahren"?

nein, das geht leider nicht
