### ISSUE TITLE
Starttext doppelt

### ISSUE THREAD

**Issue by wicoz** [wieselundco/website#9]
> - geht man in den vollständigen Eintrag rein, so erscheint der Starttext doppelt;

Ich habe den duplizierten (fett gedruckten) starttext entfernt

-> kann ich nicht bestätigen bei Stichproben

**Comment by ratnanil** [comment]
Hatte meine lokalen Änderungen noch nicht auf dem Server aktualisiert. Jetzt sollte es überall passen
